- app/styles/app.less
Closes #2573
although visited links become brighter on legacy, I think darker makes more sense?
> feat(app): 2573 visited links are darker

- app/scripts/files/files.directives.ts
Manifest fields are strictly defined within https://github.com/NCI-GDC/gdcapi/blob/fbad1249370c2a7eaa2fb1c5c58292be8fbda75a/gdcapi/download/utils.py
Tested in dev, doesn't seem to break anything, but...
r? @NCI-GDC/oicrdevs
> fix(manifest): API-58 remove fields parameter from manifest download

- app/react-components/Projects.js
- app/react-components/charts/PieChart.js
- app/react-components/charts/StackedBarChart.js
- app/react-components/charts/style.css
- app/scripts/projects/projects.controller.ts
- stacked bar chart:
* 20 genes instead of 10
* show 'no data' when loading
* correct query to pass in project id in es script
score, filter out cases with other project ids
- piechart: show hand when hovering and has callback
> :bug: project list viz fix ups

- app/react-components/Projects.js
- app/scripts/projects/projects.controller.ts
- app/scripts/projects/templates/projects.html
- 2nd fetch: reshows spinner
- seperate isFetching state for each chart
- change id of react root so if user navigates away to another page in the middle of a
fetch, the current react root isn't replaced by the charts.
noticed these things when testing on the vm. r?
> :bug: improve loading of project list viz

- modules/node_modules/@ncigdc/uikit/Notification.js
- Initialized `pageload` to be `false` so first time cart action of adding/removing file shows the notification
> :bug: [PRTL-579] Fix cart notification not showing up

- app/scripts/app.ts
- app/scripts/home/home.controllers.ts
- app/scripts/home/templates/home.html
Looks like https://github.com/NCI-GDC/portal-ui/commit/1204596d31422df214fe7a1f6632627d9d61dbe5 to get the date release date from api didn't make it into `release/1.5.0` making this PR to do that.
> [API-216] use release date from api

- modules/node_modules/@ncigdc/components/ProgressContainer.js
- modules/node_modules/@ncigdc/components/ProjectsCharts.js
- modules/node_modules/@ncigdc/containers/ProjectsPage.js
- modules/node_modules/@ncigdc/dux/relayProgress.js
Kind of an odd fix. Because the url is changing, the projects charts are re-firing, but we need to wait for the relay container to finish loading to get the returned projects.
> :sparkles: reload projects charts on query update

- modules/node_modules/@ncigdc/dux/auth.js
my bad, didn't check that auth reducer works locally after dispatching on initial load. @alex-wilmer
> 🐛  null check in auth reducer for local dev

- modules/node_modules/@ncigdc/components/QuickSearch/QuickSearch.js
> 💄 widen quicksearch box wider so ‘h’ in "Quick Search" isn’t cut off

- modules/node_modules/webpack_entry/index.html
d3tip needs d3, which is in bundle, which is placed at end of document in production build
> Defer loading d3tip script

- modules/node_modules/@ncigdc/components/GeneTable.js
- modules/node_modules/@ncigdc/components/MutationTable.js
Commented out links for following tables:
- Gene table: # Affected Cases across all project + # mutations
- Mutation table: # Affected Cases
> [PRTL-683] Exploration page link disable

- modules/node_modules/@ncigdc/dux/auth.js
alternative to https://github.com/NCI-GDC/portal-ui/pull/1261 if we can't remove the custom payload. We can handling the error produced. 
Needs to be deployed to Dev2 to test
> 🐛 handle error parsing user

- modules/node_modules/@ncigdc/components/Aggregations/DateFacet.js
- modules/node_modules/@ncigdc/components/Aggregations/FacetHeader.js
- modules/node_modules/@ncigdc/components/Aggregations/FacetResetButton.js
- modules/node_modules/@ncigdc/components/Aggregations/PrefixFacet.js
- modules/node_modules/@ncigdc/components/Aggregations/RangeFacet.js
- modules/node_modules/@ncigdc/components/Aggregations/SuggestionFacet.js
- modules/node_modules/@ncigdc/components/Aggregations/TermAggregation.js
- modules/node_modules/@ncigdc/components/Aggregations/index.js
- modules/node_modules/@ncigdc/components/FacetWrapper.js
- modules/node_modules/@ncigdc/containers/AnnotationAggregations.js
- modules/node_modules/@ncigdc/containers/CaseAggregations.js
- modules/node_modules/@ncigdc/containers/FileAggregations.js
- modules/node_modules/@ncigdc/containers/ProjectAggregations.js
- modules/node_modules/@ncigdc/theme/icons/AngleIcon.js
- modules/node_modules/@ncigdc/theme/icons/UndoIcon.js
- modules/node_modules/@ncigdc/theme/versions/active.js
got all three right hand side buttons to play nice. Had to move TermAggregation's showingValueSearch state (for the mag glass) to FacetWrapper.
> :bug: PRTL-763 fix overlap of facet reset/value search/remove buttons

- modules/node_modules/@ncigdc/components/MutationTable.js
```
Reported by Vincent.
Please update labels in table header.
In Most Frequent Mutations tables:
>>"# Affected Cases in [Project_id] Case" >> "# Affected Cases in [Project_id]" (remove Case word)
In Most Frequently Mutated Genes and Most Frequent Mutations tables:
"# Affected Cases Across all Projects" >> "# Affected Cases in all Projects" (remove Across word)
```
> :pencil: PRTL-773 update table header copy

- modules/node_modules/@ncigdc/containers/FrequentMutationsChart.js
~move the 'No mutations data found' message from `FrequentMutations` to `FrequentMutationsContainer` because it was never being reached if there were none.~
now hiding the chart when no hits. also updated the barchart herfs to onClicks
> :bug: PRTL-795 MostFrequentMutationsContainer display none message

- modules/node_modules/@ncigdc/containers/SmartSearchPage.js
test instructions: 
Go to `/repository`, select a filter, click on "Advanced Search"
> 🐛 PRTL-746 Populate advanced/smart search from jsurl filters

- modules/node_modules/@ncigdc/components/Aggregations/RangeFacet.js
input wasn't properly resetting because selectedUnit wasn't being destructured from state
> :bug: PRTL-751 clear RangeFacet inputs when query is reset

- modules/node_modules/@ncigdc/components/Pagination/Sizes.js
- modules/node_modules/@ncigdc/uikit/Pagination.js
- modules/node_modules/@ncigdc/uikit/Sizes.js
- Style was overwritten by another class so made the CSS rule `!important`
> 🐛💄 [PRTL-800 & 801] pagination selected page style change

- modules/node_modules/@ncigdc/components/GeneTable.js
- modules/node_modules/@ncigdc/components/MutationTable.js
- modules/node_modules/@ncigdc/containers/FrequentMutationsTable.js
- modules/node_modules/@ncigdc/uikit/TogglableUl.js
ticket: 
> rows are too tick. Make all row height the same across the portal. Currently summary tables and table in repository have all thiner rows which is better.
> Talked with Shane, this is due to the Survival Analysis button. 
> We can make the button smaller in Most Frequently Mutated Genes and Most Frequent Mutations table so that row height is the same for all tables.
actually it was mostly the TogglableUI's margin bottom pushing it out
> 💄 PRTL-816 reduce td height

- modules/node_modules/@ncigdc/components/QuickSearch/QuickSearch.js
- modules/node_modules/@ncigdc/components/QuickSearch/QuickSearchResults.js
- modules/node_modules/@ncigdc/utils/getIconClassNameByEntityType.js
JIRA relevant tickets:
- https://jira.opensciencedatacloud.org/browse/PRTL-854
- Add spinner
https://jira.opensciencedatacloud.org/browse/PRTL-860
- Fix bug with navigation not occurring
https://jira.opensciencedatacloud.org/browse/PRTL-861
- Only display top 5 matches
https://jira.opensciencedatacloud.org/browse/PRTL-862
> 🐛 PRTL-854 Quick Search UI fixes

- data/schema.json
- data/version.json
- modules/node_modules/@ncigdc/components/SSM.js
- modules/node_modules/@ncigdc/containers/SSMPage.js
- modules/node_modules/@ncigdc/utils/externalReferenceLinks.js
reading `dbSNP` and `COSMIC` ids as external reference for mutation.
> 🐛 [PRTL-824] Mutation external reference

- modules/node_modules/@ncigdc/components/Case.js
- modules/node_modules/@ncigdc/components/Home.js
- modules/node_modules/@ncigdc/components/Project.js
- modules/node_modules/@ncigdc/containers/CaseAggregations.js
- modules/node_modules/@ncigdc/containers/CasePage.js
- modules/node_modules/@ncigdc/containers/CaseTable.js
- modules/node_modules/@ncigdc/containers/CaseTr.js
- modules/node_modules/@ncigdc/containers/ProjectTr.js
- modules/node_modules/@ncigdc/containers/SmartSearchPage.js
- modules/node_modules/@ncigdc/containers/cohort/CaseAggregations.js
- modules/node_modules/@ncigdc/containers/cohort/CaseTable.js
- modules/node_modules/@ncigdc/containers/cohort/CaseTr.js
- modules/node_modules/@ncigdc/uikit/CollapsibleList.js
The primary site and disease type have moved to Case entity.
A project could potentially have N primary sites / N disease Types.
We have updated the UI accordingly.
This wiki describes the impacts for the UI:
https://wiki.oicr.on.ca/display/GDCSPECS/Move+Primary+Site+and+Disease+Type+to+Case+entity
> [PRTL-304] move primary site and disease type to case entity

- .gitignore
- data/schema.json
- data/version.json
- package.json
The intention here is that anytime the API graphql schema is updated, we need to update the UI anyways. This PR makes sure a fresh relay schema is created whenever the portal is booted up.
> 🔧 generate schema on start, remove from vc

- modules/node_modules/@ncigdc/components/PortalSummary.js
`>> it links to the Data Portal release notes but it should link to the Data Release notes`
> :bug: PRTL-883 correct link to data relase notes

- modules/node_modules/@ncigdc/components/ProjectVisualizations.js
- modules/node_modules/@ncigdc/containers/CancerDistributionChart.js
- modules/node_modules/@ncigdc/containers/CancerDistributionTable.js
- modules/node_modules/@ncigdc/containers/FrequentMutationsTable.js
- modules/node_modules/@ncigdc/containers/GenePage.js
This will need to be updated when `ssm_tested` turns into an array, but for now is responsible for grabbing its own agg data rather than being passed from the analysis endpoint
> 🐛 [PRTL-926] get project total ssm tested freq table

- modules/node_modules/@ncigdc/components/CancerDistribution.js
- modules/node_modules/@ncigdc/components/Oncogrid/OncogridWrapper.js
- modules/node_modules/@ncigdc/components/ProjectVisualizations.js
- modules/node_modules/@ncigdc/components/SummaryCard.js
- modules/node_modules/@ncigdc/containers/CancerDistributionChart.js
- modules/node_modules/@ncigdc/containers/FrequentMutationsChart.js
- modules/node_modules/@ncigdc/containers/FrequentMutationsTable.js
- modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesChart.js
- modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesTable.js
- modules/node_modules/@ncigdc/containers/MostAffectedCasesChart.js
- modules/node_modules/@ncigdc/containers/MostAffectedCasesTable.js
- modules/node_modules/@ncigdc/utils/withSize.js
Higher green lines (FPS) is better, shorter yellow blocks is better, shorter periods of low FPS is better, fewer solid red rectangles at the top is better 
Before:
After:
Stats (note: using timeline slows absolute performance)
Before: ~10.7s of 0 FPS, 13.8s total scripting time
After: ~4.7s of 0 FPS, 7.3s total scripting time
Should result in a shorter period where user interaction feels jolt-y
> ⚡️ PRTL-744 project page performance tweaks

- modules/node_modules/@ncigdc/containers/FilePage.js
- modules/node_modules/@ncigdc/containers/FileTable.js
- modules/node_modules/@ncigdc/dux/cart.js
- modules/node_modules/@ncigdc/utils/auth/__tests__/auth.test.js
- modules/node_modules/@ncigdc/utils/auth/index.js
- package.json
ticket says all `Data Type = Copy Number QA Metrics` files will have no projects associated, check file state and file acl instead. There doesn't seem to be any files of that type indexed currently, so wrote some tests.
> ✨ [PRTL-420] update download permission check for files with no projects

- modules/node_modules/@ncigdc/components/Layouts/FullWidthLayout.js
in firefox and IE the title bar is about 50% off
in chrome just a little bit
> 🐛 left align title bar

- modules/node_modules/@ncigdc/components/Charts/StackedBarChart.js
- modules/node_modules/@ncigdc/components/ProjectsCharts.js
- also fix flexbox of project list viz so last bar of StackedBar isn't
covered by piechart flexbox and can be clicked on laptop screen
> :bug: PRTL-1015 StackedBar add margin left so more digits fit in y-axis

- modules/node_modules/@ncigdc/components/Case.js
- modules/node_modules/@ncigdc/components/Cohort/GenesTab.js
- modules/node_modules/@ncigdc/components/Cohort/MutationsTab.js
- modules/node_modules/@ncigdc/components/ProjectVisualizations.js
- modules/node_modules/@ncigdc/containers/FrequentMutationsTable.js
- modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesTable.js
- modules/node_modules/@ncigdc/containers/GenePage.js
- modules/node_modules/@ncigdc/utils/survivalplot.js
Doesn't seem to time out anymore
I wonder what was causing this to time out before
Worst case scenario (0 filters) should also be cached by varnish so this may work
> 🎛 Increase default number of cases to fetch for survival plot to 500

- modules/node_modules/@ncigdc/containers/cohort/CohortPage.js
- modules/node_modules/@ncigdc/containers/cohort/GeneAggregations.js
- can still search by symbol
- so then links with gene_id in the filter show up in the facet panel
> :bug: PRTL-1032 suggestion facet on gene tab should add filter for gene_id

- modules/node_modules/@ncigdc/containers/MutationsCount.js
- package.json
- yarn.lock
Chrome Firefox and Safari have a limit of 6 simultaneous HTTP connections per domain
Limiting this to < 6 would prevent Mutation Count requests (40 of them in the cohort page when showing the default 20 rows per table, 20 in the project page) from blocking off other requests
4 works alright
> 🚀 Limit concurrent Mutation Count requests so it does not take up all available http connections

- modules/node_modules/@ncigdc/components/ProjectVisualizations.js
- modules/node_modules/@ncigdc/containers/MutationsCount.js
Calling setState inside withPropsOnChange is throwing an error.
> 🐛 remove setState calls from withPropsOnChange

- modules/node_modules/@ncigdc/containers/CaseAggregations.js
- modules/node_modules/@ncigdc/containers/FileAggregations.js
- modules/node_modules/@ncigdc/containers/cohort/CaseAggregations.js
Should fix issue of "Custom Facet returns no data when term selected after first added"
was not able to add test due to `TypeError: (0 , _withTooltip2.default) is not a function`
> 🐛PRTL-1109 - case aggregation returns no data when term selected after first added

- modules/node_modules/@ncigdc/containers/Lolliplot.js
~WIP~
the umd build is broken in IE, using `/dist/lib` directly
> 🐛 [PRTL-1107] use react-lolliplot/dist/lib

- modules/node_modules/@ncigdc/components/Cohort/CohortCasesCharts.js
Ticket was 'Cohort Pie Charts do not refresh', got a bit tripped up because thought the filters weren't being passed to the aggregations. They are, but https://github.com/NCI-GDC/gdcapi/blob/master/gdcapi/esutils/request.py#L196 aggregations don't filter themselves unless they are range, so it looked like the `gender` pie chart didn't update when `gender` was selected for example. Fixed by front end filtering per pie chart.
> :bug: PRTL-1045 cohort pie charts filters self

- modules/node_modules/@ncigdc/containers/CaseTr.js
- modules/node_modules/@ncigdc/containers/FileTable.js
- modules/node_modules/@ncigdc/containers/FileTr.js
We ask for annotation ids such that we can link to the annotations list page, filtered. For files specifically, we need a better solution (filter annotations by file somehow).
This solves relay trying to be smart and asking for missing annotation ids on nested case/file nodes
> 🔥 no annotation id half measure

- modules/node_modules/@ncigdc/components/File.js
- modules/node_modules/@ncigdc/containers/CaseTr.js
- modules/node_modules/@ncigdc/containers/FilePage.js
- modules/node_modules/@ncigdc/containers/FileTr.js
- modules/node_modules/@ncigdc/dux/cart.js
This removes instances of `cases.files.cases` and `files[something_nested].cases` for project info, which can be passed in from above
> 🔥♻️ get file project_info not from nested cases

- modules/node_modules/@ncigdc/components/ProjectsCharts.js
> 🎛 PRTL-1152 remove genes.is_cancer_gene_census from top charts filter

- modules/node_modules/@ncigdc/containers/FrequentMutationsTable.js
- modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesTable.js
Rely confuses me muchly. Issue was, if the 'Clear' button was clicked, the "# Affected Cases in Cohort" column in exploration Gene tab did not go back to no-query numbers. ie, if TCGA-LUAD was added as project id, and then clear is clicked this happens:
TP53 is supposed to be at the top with 3,997 / 10,196. The front end sorting didn't fix it because the numbers themselves are wrong. When `Clear` is clicked, I do see the `geneCaseFilter` correctly being reset to having no project_id. Forcing relay to refetch fixes it, but there might be a better way? :/
also added forceFetch to mutations table because that's also problematic
> :bug: PRTL-1153 force fetch filteredCases

- modules/node_modules/@ncigdc/components/Charts/BarChart.js
- modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesChart.js
~~wip~~
so that the scale's values are not super small and matches the tooltip, and the number of ticks matches survival plot
> PRTL-1172 use filtered value for explore gene chart values

- modules/node_modules/@ncigdc/containers/CancerDistributionTable.js
This was lost in a merge conflict
https://github.com/NCI-GDC/portal-ui/pull/1639/commits
> 🐛PRTL-1173 add "Available Variation Data is SSM" to filters

- webpack.dev.config.js
allows you to use http://localhost:8080 or http://192.168.*.*:8080
> ✨ enable ip to be used in addition to localhost

- src/packages/@ncigdc/components/PortalSummary.js
- set height on svg icons, else IE sets a real high height and pushes
out the layout
> 🏁 PRTL-875 homepage alignment

- src/packages/@ncigdc/containers/CancerDistributionTable.js
- fix bug where only one table row displayed
> 🐛 PRTL-1256 string (not component) as key

- src/packages/@ncigdc/dux/tableColumns.js
if a table is missing from the local storage, this will just use the default.
> Use default tables configs

- src/packages/@ncigdc/containers/Lolliplot.js
This reverts commit 62379b0e07f258b2b789db193dea58f1216680d4.
> Revert "✨ [PRTL-1260] remove impact option in lolliplot (#1774)"

- .travis.yml
- package-lock.json
- package.json
eslint fails on warnings during the Test stage
if eslint fails travis will fails immediately instead of running tests
removed lint-staged and husky. They are super heavy deps and didn't seem like they were adding much.
might need to run:
`find .git/hooks -type f ! -name '*.sample' -delete`
if husky doesn't delete its git hooks
> Travis fail early

- .vscode/settings.json
Will save me from having to stash and reapply this over and over
> 🔧 vscode autoFixOnSave

- src/packages/@ncigdc/components/PortalContainer.js
- src/packages/@ncigdc/modern_components/AffectedCasesBarChart/index.js
- src/packages/@ncigdc/modern_components/AffectedCasesTable/index.js
- src/packages/@ncigdc/modern_components/ExploreCasesPies/index.js
- src/packages/@ncigdc/modern_components/ExploreCasesTable/index.js
- src/packages/@ncigdc/modern_components/GenesBarChart/index.js
- src/packages/@ncigdc/modern_components/GenesTable/index.js
- src/packages/@ncigdc/modern_components/ProjectBreakdown/index.js
- src/packages/@ncigdc/modern_components/SsmsBarChart/index.js
- src/packages/@ncigdc/modern_components/SsmsTable/index.js
- src/packages/@ncigdc/modern_components/index.js
I've wanted to do this for a while.. a quick way to test a component by itself.
this makes a route at `/components/:component_name` and loads just that component. Should be a really good way to test default props and performance per component.. lots of things really. I was thinking about storybook for a while but this seems easier for now
> Isolated component route

- src/packages/@ncigdc/components/LoginButton.js
https://jira.opensciencedatacloud.org/browse/SV-766
phillis [3:12 PM] shared this post
Problem:
Some users can login to the portal, but can't download token nor protected files
How to trigger the bug:
This only happens if a user's previous token is expired recently. And use the data-portal's login button to login.
Reason that the user can't get token:
The login process is:
1) user clicks login in portal, portal creates a popup and redirect to /auth
2) auth server redirects user to itrust to login
3) after login, the auth server checks if the user has a valid token
a) if True, redirect back to portal. Everything good
b) if False, it calls keystone(internal auth server) to generate a new token, and save it in database, then redirect back to portal
4) the portal keep checking if the popup's …
> 🐛 [SV-766] do not close login popup on /auth

- src/packages/@ncigdc/theme/global.css
- src/packages/@ncigdc/uikit/Tooltip/GlobalTooltip.js
- src/packages/@ncigdc/uikit/Tooltip/style.css
keeps the tool tip on screen.
Example(from https://github.com/NCI-GDC/portal-ui/pull/1900):
> ✨ update tooltip positioning

- src/packages/@ncigdc/containers/explore/GeneAggregations.js
the grey reset icon now appears
> :bug: PRTL-1451 Gene facet: fix field so reset appears

- src/packages/@ncigdc/components/CurrentFilters.js
- src/packages/@ncigdc/modern_components/CreateSetButton/CreateSetButtonBase.js
My bad, the create save set button reuses the set_id between the repo and explore page if current filters only contains set id. However the check fails when a range facet is added and the type of value is not a string but a number. Fix by casting toString().
> :bug: CreateSaveSetBtn: dont die when currentFilters value is not a string

- src/packages/@ncigdc/components/TabbedLinks.js
in projects list page the class `.table` was being added which has a big margin on it
> 🐛 missing test- prefix in class causing style issue

- src/packages/@ncigdc/components/ArrangeColumns.js
'Restore Default' button in ArrangeColumns restored columns in the table, but did not in the dropdown itself. This PR fixes that but there's still an issue with the last item not being able to be dragged past the hidden items if the rest of the list is the same. Thoughts @alex-wilmer?
(changes outside of src/packages/@ncigdc/components/ArrangeColumns.js are just adding types or a setDisplayName)
> :bug: PRTL-1481 ArrangeColumns restores default in itself

- src/packages/@ncigdc/components/Modals/SaveSetModal.js
- src/packages/@ncigdc/modern_components/setButtons/SetButtonBase.js
prevents `input set` being renamed if it's the only filter
> ✨ always create new set in save set modal

- src/packages/@ncigdc/components/NotificationContainer.js
- src/packages/@ncigdc/uikit/Notification.js
My previous pr to add a condition to only mount notification when `notification.component` exists broke the first notification. The notification doesn't show until the second call to `shouldUpdate`. 
Added overflow hidden so the notification isn't visible when it's hidden.
> 🐛 always mount notification

- src/packages/@ncigdc/components/PortalContainer.js
removes these scrollbars that appear when the mouse is near the edge.
> 🐛 overflow hidden to prevent tooltip causing scrollbars

- data/schema.graphql
- data/schema.json
- package-lock.json
- src/packages/@ncigdc/components/DownloadButton.js
- src/packages/@ncigdc/routes/ManageSetsRoute/ManageSetsPage.js
requires https://github.com/NCI-GDC/gdcapi/pull/845. 
A tar with all the cases, all the genes and 50K mutations takes 58s to start streaming. Can't start streaming right away because the TarStream function needs to know the full contents size before it starts, otherwise tar will be incomplete/garbage.
> :sparkles: PRTL-1655 download all sets in a tar

- src/packages/@ncigdc/components/SetTable.js
otherwise it craps out for the Remove button if there is only one set
> :bug: PRTL-1835 SetsTable: use defaultProps for optional getDisabledMessage prop

- src/packages/@ncigdc/components/Modals/UploadSet/CreateSetButton.js
- Submit stays disabled when has name but no validated hits
The other issue in the ticket was a varnish cache issue, fixed with varnish restart.
> :bug:PRTL-1831: UploadAndSaveModal, fix Submit disable

- src/packages/@ncigdc/components/CurrentFilters.js
advance search parser removes [" if upper case IN, doesn't if lowercase. Which is what's needed for the set ids to work there :woman_shrugging:
> :bug: PRTL-1833 fix advance search button for set ids

- package-lock.json
- package.json
- src/packages/@ncigdc/components/FacetSelection.js
- src/packages/@ncigdc/components/QuickSearch/QuickSearchResults.js
- src/packages/@ncigdc/modern_components/BiospecimenCard/BioTreeItem.js
- src/packages/@ncigdc/uikit/Highlight.js
react-highlight started causing biospec tree & custom facet search pages to error out, we had our own inside quicksearch. Moved that out into its own component and replaced react-highlight.
> :fire: PRTL-1866 replace react-highlighter with our own

- src/packages/@ncigdc/modern_components/CohortComparison/CohortComparison.js
- src/packages/@ncigdc/modern_components/CohortComparison/FacetTable.js
- show 2 decimal places for percentages
- fix filter link for age of diagnosis
instead of
> :bug: PRTL-1856 fix age diagnosis display years

- src/packages/@ncigdc/components/DownloadButton.js
- src/packages/@ncigdc/components/analysis/SetOperations/OpsTable.js
- src/packages/@ncigdc/routes/ManageSetsRoute/ManageSetsPage.js
- src/packages/@ncigdc/utils/download/index.js
for large sets, sometimes the streamed tsv file cut off without all the ids, but the tar_set endpoint which skips the filter and downloads sets directly always worked. Changed the tar_set endpoint to not tar if only one set in payload https://github.com/NCI-GDC/gdcapi/pull/868
done in manage set page, analysis page pending
> :bug: PRTL-1888 fix large set id downloads

- src/packages/@ncigdc/modern_components/GeneSummary/GeneSummary.js
Sets census value to string 'true'.
> 🐛 [PRTL-1933] - Fixes blank page when cancer-gene-census unchecked.

- src/packages/@ncigdc/modern_components/ExploreCasesTable/ExploreCasesTable.model.js
- src/packages/@ncigdc/modern_components/RepoCasesTable/RepoCasesTable.model.js
tsv export querySelects the dom nodes and then writes values to tsv, in the DOM the slide count is displayed with ()s but excel displays numbers with () as negative :sweat_drops:, the `ForTsvExport` component tells Tsv exporter what to write instead of DOM value.
> 2075 custom tsv slide count

- src/packages/@ncigdc/components/Aggregations/ExactMatchFacet.js
- src/packages/@ncigdc/components/Aggregations/RangeFacet.js
To avoid empty search request, set query value to null when the input value for a GoLink component is empty in both RangeFacet and ExactMatchFacet.
> :bug [PRTL-2083] Disable the GoLink Button when the input value is empty.

- src/packages/@ncigdc/modern_components/ExploreCasesTable/ExploreCasesTable.model.js
Added naxWidth with 130 px for primary_site column in ExploreCasesTable and added a tooltip to show the full content if overflow happens.
>  [PRTL-2054] Set max width and overflowTooltip to primary site column

- src/packages/@ncigdc/components/Charts/PieChart.js
Changes I made:
- remove half-degree padding from the size of slices
- add a white border to the style of slices
Before:
After:
> 🐛 [PRTL-1923] adjust pie chart whitespace

- public/robots.txt
Add a `robots.txt` file to stop search engines from crawling past the home page.
Googlebot recently crawled around the exploration page for a while and generated a bunch of increasingly complex Elasticsearch queries. This should stop legitimate search indexes from doing that.
> 🛠 [GDCDEVOPS-160] add robots.txt

- src/packages/@ncigdc/components/ArrangeColumns.tsx
- src/packages/@ncigdc/components/ArrangeColumnsButton.js
- src/packages/@ncigdc/components/TableActions.tsx
- src/packages/@ncigdc/modern_components/GenesTable/GenesTable.model.tsx
- src/packages/@ncigdc/modern_components/SsmsTable/SsmsTable.js
In case entity page and gene entity page
> [PRTL-2281] Hide Survival selectable columns from arrange column button

- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard.js
Leaving it at `overflow: auto` seems to take care of the problem well enough.
Will amend if testing finds unforeseen side-effects.
> PRTL-2517 remove unnecessary layout breaking scrollbars

- .eslintrc.js
- package-lock.json
- package.json
- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalAnalysisResult.js
- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard.js
- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ContinuousAggregationQuery.js
- modifies the query to gather the required additional fields.
> PRTL-2544 add data for Box Plot + Table

- src/packages/@ncigdc/components/Charts/BarChart.js
PRTL-2598
X-axis labels on the survival plot can now be 10 characters before they're truncated.
> change x-axis length from 8 to 10

- data/getSchema.js
- data/schema.graphql
- data/schema.json
- src/packages/@ncigdc/components/EntityPageVerticalTable.js
- src/packages/@ncigdc/modern_components/GeneExternalReferences/GeneExternalReferences.js
- src/packages/@ncigdc/modern_components/GeneExternalReferences/GeneExternalReferences.relay.js
- src/packages/@ncigdc/modern_components/GeneExternalReferences/index.js
- src/packages/@ncigdc/modern_components/GeneSummary/GeneSummary.js
- src/packages/@ncigdc/modern_components/GeneSummary/GeneSummary.relay.js
- src/packages/@ncigdc/modern_components/GeneSummary/index.js
- src/packages/@ncigdc/modern_components/SsmExternalReferences/SsmExternalReferences.js
- src/packages/@ncigdc/modern_components/SsmExternalReferences/SsmExternalReferences.relay.js
- src/packages/@ncigdc/modern_components/SsmExternalReferences/index.js
- src/packages/@ncigdc/modern_components/SsmSummary/SsmSummary.js
- src/packages/@ncigdc/modern_components/SsmSummary/SsmSummary.relay.js
- src/packages/@ncigdc/modern_components/SsmSummary/index.js
- src/packages/@ncigdc/routes/GeneRoute/GeneRoute.tsx
- src/packages/@ncigdc/routes/GeneRoute/index.tsx
- src/packages/@ncigdc/routes/SSMRoute/SSMRoute.js
- src/packages/@ncigdc/routes/SSMRoute/index.js
- src/packages/@ncigdc/utils/externalReferenceLinks.js
PRTL-2534
Adds relevant queries (though genes' uses aggregation from ssms, which disrupts the *-centric indexing pattern); and display the data when available in both of the entity views as instructed in the requirement.
> [PRTL-2534] add CIViC to gene and ssm entity views

- src/packages/@ncigdc/components/Aggregations/NotMissingFacet.js
- src/packages/@ncigdc/components/Aggregations/RangeFacet.js
- src/packages/@ncigdc/components/Aggregations/TermAggregation.js
- src/packages/@ncigdc/components/FacetWrapper.js
- src/packages/@ncigdc/components/SearchPage.js
- src/packages/@ncigdc/containers/explore/CaseAggregations.js
- src/packages/@ncigdc/containers/explore/CaseAggregations.tsx
- src/packages/@ncigdc/containers/explore/ClinicalAggregations.tsx
- src/packages/@ncigdc/containers/explore/GeneAggregations.js
- src/packages/@ncigdc/containers/explore/SSMAggregations.js
- src/packages/@ncigdc/modern_components/CaseAggregations/CaseAggregations.js
- src/packages/@ncigdc/modern_components/FileAggregations/FileAggregations.js
e.g. PRTL-2646
Adds border to facet wrapper component, removes double border on facets in explore and repository
Shrinks padding on explore facet tab links so there's room for the minimize chevron button
> 💄PRTL-2646 clinical tab divider lines

- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js
- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ContinuousAggregationQuery.js
PRTL 2666
Make 5 continuous bins by default instead of 4.
The custom binning modal still uses quartiles.
> [PRTL 2666] 5 continuous bins

- src/packages/@ncigdc/components/Modals/ContinuousBinning/ContinuousCustomBinsModal.js
- src/packages/@ncigdc/dux/analysis.ts
- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js
- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ContinuousAggregationQuery.js
- src/packages/@ncigdc/utils/string.ts
PRTL-2675
1. Fail gracefully if there's no data in continuous facets. 
2. When changing cohorts, update the buckets & disable the reset button.
3. Change continuous ranges to work with the API.
4. Only do rounding/parsing for display purposes (e.g. `groupName`), or to calculate the number of buckets (since that needs to be an integer)
5. Fix tooltip on survival plot selector button
> [PRTL-2675] fix issue with empty cards

- src/packages/@ncigdc/modern_components/SsmsTable/SsmsTable.model.js
PRTL-2546
Survival plot slug will display `consequence_type` when `aa_change` is not present
> 🐛 PRTL-2546 add consequence_type fallback to survival plot slug

- src/packages/@ncigdc/tableModels/utils.tsx
- src/packages/@ncigdc/utils/constants.js
SV-1480
Add optional key for category columns to remove link from column total. Default is true.
Addresses bug in filters for project clinical/bio totals.
> 🚑 PRTL-2716 Remove link from clinical and bio totals

- data/getSchema.js
- data/schema.graphql
- data/schema.json
- src/packages/@ncigdc/components/EntityPageHorizontalTable.js
- src/packages/@ncigdc/modern_components/ClinicalCard/ClinicalCard.js
- src/packages/@ncigdc/modern_components/ClinicalCard/ClinicalCard.relay.js
- src/packages/@ncigdc/uikit/Tabs.js
PRTL-2704
Adds follow_up and molecular_test nodes to case page. Mol tests are nested under follow_up
Rebuilds schema to include these nodes. Civic schema updates included from `dev-oicr`
Updates treatment table to EntityPageHorizontal component for more consistency with other clinical node tables
> ✨PRTL-2704 nest molecular under followup

- package-lock.json
- package.json
PRTL-2511
- update `react-lolliplot` version
> [PRTL-2511] make lolliplot backbone work in firefox

- src/packages/@ncigdc/components/PortalContainer.js
Wrong Back Button & Navigation Behaviour on Exploration
The issue is generated by shouldComponentUpdate function in PortalContainer.
When back button is clicked on the browser, the url changes to the previous url.
PortalContainer should refresh the page but it has been restricted by shouldComponentUpdate to only refresh the page when notifications changes.
So the solution is to change shouldComponentUpdate to also listen to changing of location prop which has the information of url.
> [PRTL-2774] Wrong Back Button & Navigation Behaviour on Exploration

- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/EnhancedClinicalVariableCard.js
Restores the survival plot updates for custom categorical bins.
> [PRTL-2827] fix survival plot for custom categorical bins

- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/ContinuousVariableCard.js
Calculates the values correctly for Years of Diagnosis.
TODO: Must remove this hack whenever API makes the units available
> [PRTL-2779] fix Years of Diagnosis unit

- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/components/ClinicalHistogram.js
- [] `qa` (which version?)
add right `font-weight` in the specific context.
> [PRTL-2770] make x-axis font bold at clinical analysis histogram

- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/EnhancedClinicalVariableCard.js
PRTL-2831
listen for `filters` prop changes before running `populateSurvivalData`. it contains the `setId` and is passed to the survival plot. this way the survival plot will update when you change case sets regardless of the values/fields being passed.
> [PRTL-2831] categorical survival doesn't plot unless fields change

- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/modals/ContinuousCustomBinsModal/ContinuousCustomBinsModal.js
PRTL-2847
- rewrote the custom interval validation to use regexes instead of `Number()` and lodash `isFinite`
- added comments and tried to make things clearer overall
> [PRTL-2847] custom interval validation

- src/packages/@ncigdc/components/Charts/PieChart.js
- src/packages/@ncigdc/components/Explore/SummaryPage/CardWrapper.js
- src/packages/@ncigdc/components/Explore/SummaryPage/HistogramCard.js
- src/packages/@ncigdc/components/Explore/SummaryPage/index.js
PRTL-2843
- rename Data Types to Experimental Strategies
- remove redundant X-axis labels (i.e. Race & Gender have the same title & X-axis)
- set default X-axis prop
- for donut charts, create colours and pass them down with data, and add them to TSV
- update `PieChart` to accept data with color info
- remove tooltip from TSV
> [PRTL-2843] summary page card cleanup

- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ControlPanel/ControlPanelNode.js
This check didn’t account for the current_analysis ID being changed for some unexplainable reason (which is truly a symptom of a deeper problem).
To keep this issue’s scope, I’m just loosening the check. 
The source problem, remains as technical debt.
> [PRTL-2856] reduce restrictive lifecycle check

- src/packages/@ncigdc/theme/global.css
Enhances word breaking and wrapping capabilities to the projects table
> [PRTL-2858] wrap and hyphen words in projects table.

- src/packages/@ncigdc/components/Aggregations/NotMissingFacet.js
- src/packages/@ncigdc/containers/explore/SSMAggregations.js
The facets have independent methods per facet, rather than detecting the facet's identifier in a DRY manner. Thus, when adding this facet, the method for cosmic was copy-pasted, without updating the to the right method.
> [PRTL-2840] correct collapse method and state for dbSNP facet

- src/packages/@ncigdc/modern_components/ProjectPrimarySitesTable/ProjectPrimarySitesTable.model.js
PRTL-2873
- check for graphql response & make the check case-agnostic
- renamed unclear `k` variable
- counts in table should now be the same on prod, dev-oicr, and qa-yellow
> [PRTL-2873] fix primary site data table on project page

- src/packages/@ncigdc/utils/constants.js
Reverts the "sorting" of the object keys, as the view relies on this faux-order to display some rows and columns in a couple tables.
Must implement an appropriate sorting solution at a later stage.
> [PRTL-2865] revert changes in the category object

- src/packages/@ncigdc/modern_components/ProjectPrimarySitesTable/ProjectPrimarySitesTable.model.js
Though I'm not happy with this solution, I've resorted to this simple manipulation of the query strings at their source to resolve the issue.
A more elegant casing guard applied at the offending component (pie chart) would've created conflicts with the unnormalised data for other pies (e.g. project names); which in turn would've required logic changes beyond the scope of this ticket.
> [PRTL-2874] ensure primary site pies render properly

- src/packages/@ncigdc/utils/wrapSvg.js
PRTL-2869
made svg download titles 400 weight instead of 300
> [PRTL-2869] make svg/png title normal weight

- src/packages/@ncigdc/components/Oncogrid/dataMapping.js
Another case of mismatch between the unnormalised genes vs the normalised data.
More case guards. This one was harder to find. Funny how much difference a couple lines can make.
> [PRTL-2875] improve case guarding for OncoGrid buildOcurrences

- src/packages/@ncigdc/components/Charts/DoubleRingChart.js
- src/packages/@ncigdc/components/Charts/PieChart.js
PRTL-2828
- add a message to the double donut telling people to download the TSV
- added it to pie chart too
> [PRTL-2828] add download message to double donut & pie chart

- src/packages/@ncigdc/components/SurvivalPlotWrapper.js
- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalAnalysisResult.js
- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/ClinicalVariableCard.js
- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/components/ClinicalBoxPlot.js
- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/components/ClinicalSurvivalPlot.js
- src/packages/@ncigdc/modern_components/ClinicalAnalysis/boxplot.css
- src/packages/@ncigdc/modern_components/ClinicalAnalysis/helpers.js
PRTL-2870
- change the `print` button at the top right of clinical analysis to `download all images`
- add a slug to survival plot, so survival plot images have unique file names and are easier to select with CSS selectors
> [PRTL-2870] download all svg/png

- src/packages/@ncigdc/components/Charts/BarChart.js
- src/packages/@ncigdc/components/SurvivalPlotWrapper.js
PRTL-2885
- add color to borders in bar chart download (same as the display version of the chart)
- add a default prop for buttonStyle because clinical analysis is crashing on develop branch
> [PRTL-2885] add color to x-axis of bar chart 

- src/packages/@ncigdc/components/SurvivalPlotWrapper.js
- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/ContinuousVariableCard.js
PRTL-2886
- add default for buttonStyle because the page was crashing
- change survival bin custom flag logic: once you select/deselect a plot, survival is flagged 'custom' until the entire card is reset
> [PRTL-2886] show overall survival when no plots are selected

- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/CategoricalVariableCard.js
- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/ContinuousVariableCard.js
- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/EnhancedClinicalVariableCard.js
PRTL-2910
if survival isn't active when a clinical analysis card mounts, return empty arrays for the plot & table, and don't populate the card with any survival data.
this will prevent the cards from making unnecessary requests to the survival endpoint.
also I noticed one of the props/nextProps checks had a typo so I fixed it.
> [PRTL-2910] only make survival API requests when survival is active

- src/packages/@ncigdc/components/Aggregations/FacetHeader.js
- src/packages/@ncigdc/components/Aggregations/index.js
- src/packages/@ncigdc/uikit/Form/Input.js
PRTL-2614
- remove backgrounds so that backgrounds & borders don't overlap when zoomed @ 80%
- change px to rem to make form inputs consistent with form buttons
> [PRTL-2614] fix styling overlaps in exploration

- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ContinuousAggregationQuery.js
PRTL-2917
- continuous card was remounting because of conditional rendering, so I removed that
- if you pass down the `isLoading` prop, it will show a spinner icon that is already in the render
> [PRTL-2917] stop continuous card remounting

- src/packages/@ncigdc/components/analysis/AnalysisResult.js
- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/components/ClinicalBoxPlot.js
Removes an unnecessary minimum width enforcement, thus unblocking the container resizing.
> [PRTL-2928] ensure the analysis container adjusts to the screen size

- src/packages/@ncigdc/modern_components/Lolliplot/Lolliplot.js
PRTL-2968
if you click a single point in lolliplot, clear any point collisions in state, so the message showing the previously selected points will go away.
> [PRTL-2968] clear lolliplot collisions

- src/packages/@ncigdc/modern_components/CohortComparison/CohortComparison.js
- src/packages/@ncigdc/modern_components/CohortComparison/CohortComparison.relay.js
PRTL-3032
I changed Cohort Comparison to use 1 decimal point for Age at Diagnosis, as we established in Clinical Analysis.
It was using integers for Explore links and several decimal points for the query, which was creating inconsistencies in the number of cases in each bucket.
> [PRTL-3032] Cohort Comparison: make Age @ DX cases match Explore

- src/packages/@ncigdc/components/Explore/GenesTab.js
- src/packages/@ncigdc/containers/explore/ExplorePage.js
- src/packages/@ncigdc/modern_components/GenesBarChart/GenesBarChart.js
- src/packages/@ncigdc/modern_components/RestrictionMessage/index.js
Adds the Study relay hack to the histogram.
Removes the CA restriction message (as there was no use case for it).
> [PRTL-3093] add Study param to Most Mutated Genes histogram

- src/packages/@ncigdc/components/Explore/GenesTab.js
- src/packages/@ncigdc/utils/survivalplot.js
Adds the Study param functionality to all survival plots, and enables it for the one in Exploration's Genes tab.
> [PRTL-3095] add Study param to Genes Survival plot

- src/packages/@ncigdc/components/Modals/ControlledAccess/ControlledAccessModal.js
- src/packages/@ncigdc/utils/constants.js
- src/packages/@ncigdc/utils/withControlledAccess/helpers.js
- src/packages/@ncigdc/utils/withControlledAccess/index.js
Adds helper to check if any CA study includes the prefix "_demo" (casing-agnostically), and removes it when autoselecting the corresponding filter.
> [PRTL-3128] add CA hack for demo CA studies

- .travis.yml
- src/packages/@ncigdc/components/analysis/availableAnalysis.js
Updates the demo set name, and fixes a travis warning.
> [PRTL-3121] update Set Operations Demo, varscan is “deprecated”

- src/packages/@ncigdc/components/Header/SectionBanner.js
- src/packages/@ncigdc/components/Header/index.js
- src/packages/@ncigdc/components/Modals/ControlledAccess/ControlledAccessModal.js
- src/packages/@ncigdc/utils/withControlledAccess/index.js
- Removes an unnecessary call to one of the CA endpoints, by putting it behind the corresponding feature flag.
Bonus: a couple other fixes to ensure no crashes happen if the flag is added while the CA endpoints are not available.
> [PRTL-3151] remove stray CA request.

- src/packages/@ncigdc/components/ZoomableImage.js
Adds a codeguard to a piece of code that was stopping script execution, and relocated the conflicting function down in the script, where it wouldn't conflict if the codeguard is insufficient.
> [PRTL-3153] add codeguard to restore slide viewer

- Jenkinsfile
Changing Jenkinsfile to use the develop branch of the Jenkins pipelines.
> Change jenkins to use master branch of jenkins-lib

- src/packages/@ncigdc/components/CreateOrOpenAnalysis.js
- src/packages/@ncigdc/components/analysis/CreateAnalysis.js
- src/packages/@ncigdc/components/analysis/DemoButton.js
- src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalAnalysisResult.js
TL;DR: a few Redux action dispatchers were being incorrectly used as `thenables`, even though they were all dispatching a thunk without returning a promise.
Checked all dispatchers throughout the app, to ensure their validity.
Found only 4 offending dispatchers, all of which used the same single action thunk related to analyses.
...
Explanation of the bug: In order for a Redux dispatch to be made "thenable", the action creator MUST return a promise (and may be done with observables?); which was never the case in the codebase, yet somehow worked until now. ¯\(ツ)/¯
Such dispatchers stopped working as a result of updating some dependencies when working on AWG token renewal (needed to correct a race condition that blocked implementation).
Redux-api-middleware, in an outdated beta version, …
> [PRTL-3236] remove malfunctioning dispatch thens

- src/packages/@ncigdc/modern_components/GeneExpression/GeneExpression.js
- src/packages/@ncigdc/modern_components/GeneExpression/GeneExpressionChart.js
- src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js
- src/packages/@ncigdc/modern_components/GeneExpression/index.ts
Adds a loading spinner on first render, remains while the data is being gathered and processed, and removed once inchlib is ready to be displayed.
> [PRTL-3233] improve GeneEx loading spinner

- src/packages/@ncigdc/modern_components/GeneExpression/GeneExpressionChart.js
- src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js
Recalculates the colour ranges around 0 (rather than finding the middle value between min and max), to match our median centring algorithm.
> [PRTL-3235] mean centering of colours in GE heatmap

- src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js
Adds screen reader-friendly button labels.
> [PRTL-3238] improve Gene Expression toolbar accessibility

- src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js
PRTL-3244
- determine outer dendrogram line more reliably
- remove click events and cursor
- change text of tooltips
- handle situations like clicking on inner dendrogram to select it -> then clicking on outer dendrogram to de-select the first one
- reposition tooltips for row dendrograms
> [PRTL-3244] outer dendrogram line enhancements

- src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js
Reverses the scale fill direction, the order of the ticks' values, and gets rid of one of the ugly imperative "for" loops.
> [PRTL-3250] reverse heatmap colour scale

- src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js
Got the display wrong in the scale. This reverses it.
> [PRTL-3283] correct GeneEx scale’s inverted colours

- src/packages/@ncigdc/modern_components/SCRNASeq/helpers.js
e.g. PRTL-0000
Parses the TSV stream, ignoring empty rows.
> [PRTL-3289] handle empty TSV rows for scRNA

- awgportal.Dockerfile
- portal.Dockerfile
GDCDEVOPS-572
Add registry argument in docker builds for portal. These dockerfiles are only used in Jenkins and not travis.
> Add registry arg in docker builds for portal

- package-lock.json
- src/packages/@ncigdc/components/FacetWrapper.js
- src/packages/@ncigdc/components/__tests__/FacetWrapper.tests.js
- src/packages/@ncigdc/containers/FileAggregations.js
In DR 27, we updated some of mapping property types to double. This
was needed to perform aggregation without bucketing into integers.
As a result, custom facets broke because they did not support doubles.
> DEV-524 support range facet for doubles

- helm-jenkins.sh
- package-lock.json
- package.json
We use npm-force-resolutions to modify package-lock.json in npm preinstall. This step `npx npm-force-resolutions` has been failing when run from behind our proxy due to (what i think is) this [hard timeout.](https://github.com/rogeriochaves/npm-force-resolutions/blob/master/src/npm_force_resolutions/core.cljs#L70) I believe this is true because the command fails in 8-9secs. Also I when i used an older version of npm-force-resolutions which doesnt have that timeout, it passes. 
Filed issue https://github.com/rogeriochaves/npm-force-resolutions/issues/33 and PR https://github.com/rogeriochaves/npm-force-resolutions/pull/34/files  in upstream repo.
> Removed npm-force-resolutions  from preinstall

- src/packages/@ncigdc/utils/externalReferenceLinks.js
Update Ensembl links to point to release 102 (november 2020 archive) which corresponds to the GENCODE v36 release
> DEV-1042: Update Ensembl links in portal

- src/packages/@ncigdc/utils/openAuthWindow.js
Once MFA is enabled in the NIH IdP, the content of the login window
will require a larger window. This commit increase the size to a
decent height and width.
> PEAR-382 increase auth window size

- Jenkinsfile.security
Ticket: https://jira.opensciencedatacloud.org/browse/GDCPE-617
Removing Jenkinsfile.security as it is no more required. The file was being used by Veracode to scan code but we have moved to Synk for code scanning now
> Removing Jenkinsfile.security

- package.json
- portal.Dockerfile
Previously, the portal used absolute urls for api and auth base urls. This commit changes those to relative urls. This will allow us to deploy the docker image into different environments without needing environnemt specific configs. This change also chages the direct-api call for tiles the portal-proxied api path.
e.g. PRTL-0000
> PEAR-861 configure portal to use relative urls

- build.sh
A previous commit updated the portal.Dockerfile to use relative urls. That is the file used by Jenkins. This travis build uses the build.sh script and Dockerfile. For this commit, I'm updating the build script. I am not changing the way different build systems orchestrate their builds.
> PEAR-861 use relative urls in build script

- src/packages/@ncigdc/modern_components/Exists/exists.relay.js
with the graphene v1.4.1, it is now asking for `id: ID!` for the node field.
> DEV-1822 try to see if this fixes the ID problem
