app/scripts/annotations/templates/annotations.html
app/scripts/components/charts/chart.directives.ts
app/scripts/projects/templates/projects.html
app/scripts/search/search.controllers.ts
app/scripts/search/templates/search.html
app/styles/app.less
app/styles/search.less

feat(app): 640 expand / collapse facet sidebar

---

app/scripts/annotations/annotations.table.model.ts
app/scripts/cart/cart.table.model.ts
app/scripts/files/templates/file.html
app/scripts/participant/templates/participant.html
app/scripts/projects/projects.table.service.ts
app/scripts/search/search.cases.table.service.ts
app/scripts/search/search.files.table.model.ts
app/styles/tables.less

fix(table): truncated cell fit UUID, break longer

---

app/scripts/components/ui/biospecimen/biospecimen.controllers.ts
app/scripts/components/ui/biospecimen/biospecimen.services.ts
app/scripts/components/ui/biospecimen/tests/biospecimen.services.tests.js

fix(tree): 2572 expand first entity with children

---

app/scripts/annotations/module.ts
app/scripts/annotations/templates/annotation.html

feat(annotation): 747 case submitter_id in table

---

app/scripts/components/facets/facets.controllers.ts
app/scripts/components/facets/facets.directives.ts
app/scripts/components/facets/styles/facets.less
app/scripts/components/facets/templates/add-custom-facets-panel.html
app/scripts/components/facets/templates/add-facets-modal.html
app/scripts/search/templates/search.html

- tab cycles down after visiting input and checkbox
Closes #2517

fix(customFacet): 2517 can tab in modal

---

app/scripts/cart/cart.controllers.ts
app/scripts/cart/cart.directives.ts
app/scripts/cart/templates/add-to-cart-all-button.html
app/scripts/components/tables/tables.controllers.ts
app/scripts/components/tables/templates/gdc-table.html
app/scripts/participant/templates/participant.html
app/scripts/query/templates/query.summary.html
app/scripts/search/templates/search.files.html
app/scripts/search/templates/search.participants.html
app/scripts/search/templates/search.summary.html

- disable 'Add all to cart' when no files
- cleanups to gdc-table
Closes #2586

feat(search): 2586 missing msg

---

app/scripts/files/module.ts
app/scripts/files/templates/file.html

feat(file): 2536 show archive sub id & revision

---

app/scripts/components/header/templates/header.html
app/scripts/home/templates/home.html

fix(app): 2588 move website icon up

---

app/scripts/components/facets/facets.controllers.ts
app/scripts/components/quick-search/quick-search.directives.ts

- remove ctrl+space listener (didn't work)
Closes #2513

fix(quicksearch): 2513 unhighlight, open on enter

---

app/scripts/app.ts
app/scripts/components/facets/facets.controllers.ts
app/scripts/components/quick-search/quick-search.directives.ts
app/scripts/components/user/user.services.ts
app/scripts/core/core.services.ts
app/scripts/core/tests/core.tests.js
bower.json
karma.conf.js

- retries errored calls waiting between 1 to 5s
Closes #2393

feat(app): 2393 retry api calls

---

app/scripts/components/facets/facets.directives.ts
app/scripts/components/facets/templates/facets-free-text.html

feat(facet): 2405 open typeahead on input click

---

app/scripts/annotations/templates/annotation.html

fix(annotation): PRTL-182 no word break in notes

---

app/scripts/components/gql/module.ts

feat(autocomplete): PRTL-123 close the dropdown

---

app/scripts/components/facets/templates/add-facets-modal.html

to be consistent with https://github.com/NCI-GDC/portal-ui/commit/1cdccd50dec123bedc7f8212c2789b8e42d291d6

fix(customFacets): also use actual checkbox

---

app/scripts/components/facets/templates/add-facets-modal.html
app/scripts/files/templates/file.html

fix(file): PTRL-86 hide padding if 0 assoc cases

---

app/scripts/components/gql/module.ts
app/scripts/components/gql/tests/gql.service.tests.js

feat(gql): 2350 find/report bogus fields.

---

app/scripts/components/tables/templates/gdc-table.html

feat(export): 1892 restored large-dataset download

---

app/scripts/cart/cart.directives.ts
app/scripts/cart/cart.services.ts
app/scripts/components/downloader/downloader.directive.ts
app/scripts/core/core.controller.ts
app/scripts/core/core.directives.ts
app/scripts/core/core.services.ts
app/scripts/core/templates/generic-warning.html
app/scripts/files/files.controllers.ts
app/scripts/files/files.directives.ts
app/scripts/files/files.services.ts

feat(download): 2468 bam slicing download enhancement

---

app/scripts/home/templates/home.html

feat(home): PRTL-194 update release info

---

app/scripts/files/templates/file.html

feat(file): PRTL-75 link to source if 1 file

---

app/scripts/search/module.ts
app/scripts/search/search.controllers.ts
app/scripts/search/templates/search.html

feat(search): PRTL-147 save facet tab in url state

---

app/scripts/components/gql/module.ts
gql.pegjs

feat(gql): 1778 allows file size unit

---

app/scripts/components/header/templates/header.html
app/scripts/core/core.directives.ts

Tabbing over and pressing enter on Login, Download Token and Logout is the same as clicking

feat(header): PRTL-136 login opens on enter

---

CHANGELOG.md
app/index.html
app/scripts/components/header/header.controller.ts
app/scripts/components/header/templates/header.html
app/scripts/core/core.controller.ts
app/styles/app.less
app/styles/header.less
app/styles/theme.less
package.json

feat(app): PRTL-172 legacy data banner

---

CHANGELOG.md
app/scripts/components/header/templates/header.html
package.json

fix(app): PRTL-237 banner about portal status

---

CHANGELOG.md
app/scripts/components/header/templates/header.html
package.json

fix(app): PRTL-237 can't find data banner

---

app/scripts/components/tables/tables.controllers.ts
app/scripts/components/tables/templates/gdc-table.html

refactor(sort): PTRL-116 remove unused save code

---

app/scripts/cart/templates/cart.html
app/scripts/files/templates/download-manifest-info.html

feat(app): PRTL-146 update dl manifest text

---

app/scripts/components/facets/facets.services.ts

feat(customFacets): PRTL-67 filename as id facets

---

app/scripts/components/facets/facets.controllers.ts
app/scripts/components/facets/templates/range-facet.html

feat(rangeFacet): PRTL-77 show warning for age>=90

---

app/scripts/annotations/templates/annotation.html
app/scripts/components/quick-search/quick-search.directives.ts
app/scripts/components/quick-search/templates/annotation.html
app/scripts/components/quick-search/templates/quick-search-dropdown.html
app/scripts/projects/templates/project.html
app/styles/app.less

requires https://github.com/NCI-GDC/gdcapi/pull/577/files
only problem is the icon for annotations is a png not a font 😓

feat(quicksearch): PRTL-29 support annotations

---

app/scripts/components/ui/biospecimen/biospecimen.services.ts
app/scripts/files/files.controllers.ts
app/scripts/files/files.services.ts
app/scripts/files/module.ts
app/scripts/files/templates/file.html

- search biospecimen for the entity id then show the sample type from
sample, if it's a case show '--'

feat(file): PRTL-42 add sample type

---

.gitignore
app/scripts/home/home.controllers.ts

fix(app): fix page title

---

app/scripts/files/files.directives.ts

fix(manifest): dont allow DL when in progress

---

app/scripts/components/facets/facets.controllers.ts
app/scripts/components/facets/facets.directives.ts
app/scripts/components/facets/styles/facets.less
app/scripts/components/facets/templates/facet-heading.html
app/scripts/components/facets/templates/facet.html
app/scripts/components/facets/templates/facets-section.html
app/scripts/projects/templates/projects.facets.html
app/scripts/search/search.cases.table.service.ts
app/scripts/search/search.files.table.model.ts
app/styles/app.less

feat(facets): PRTL-21 term value search if n >= 20

---

app/scripts/participant/templates/participant.html

feat(case): [PRTL-3] remove dates from case page

---

app/scripts/cart/cart.table.model.ts
app/scripts/cart/templates/cart.html
app/scripts/components/facets/templates/current.html
app/scripts/components/header/header.controller.ts
app/scripts/components/header/templates/header.html
app/scripts/search/search.cases.table.service.ts
app/scripts/search/search.files.table.model.ts

- removes UI for My Projects Filter but leaves logic
Closes #PRTL-174

fix(app): [PRTL-174] hide my projets filter

---

app/scripts/components/gql/module.ts

- delays check until fields are returned
Closes PRTL-284

fix(smart): [PRTL-284] fix smart search fieldcheck

---

app/scripts/components/facets/styles/facets.less

fix(facets): PRTL-290 not cutoff anymore

---

app/index.html
app/scripts/components/header/header.controller.ts
app/scripts/components/header/header.directive.ts
app/scripts/components/header/templates/banner.html
app/scripts/components/header/templates/header.html
app/scripts/components/header/tests/header.tests.js
app/scripts/core/core.controller.ts
app/styles/app.less
app/styles/header.less

feat(header): PRTL-119 notifications from endpoint

---

app/react-components/Gene.js
app/react-components/Mutation.js
app/react-components/index.js
app/react-components/utils/externalReferenceLinks.js
app/scripts/app.ts
app/scripts/mutations/module.ts
app/scripts/mutations/mutations.controllers.ts
app/scripts/mutations/templates/mutation.html

- move externalReferenceLinks to util

feat(mutation): PRTL-357 add pg w/ summary

---

app/index.html
app/scripts/home/templates/home.html

angular in ie wasn't evaluating expression in template style attribute, changed to ng-style - working.

fix(app): PRTL-374 ie padding issue

---

app/scripts/genes/module.ts
app/scripts/mutations/module.ts
app/scripts/projects/module.ts

but don't have case.project.project_id in rebuilt gene index, gene page & top mutated genes barchart not working

use config.es_host

---

app/react-components/Gene.js
app/react-components/Mutation.js
app/scripts/genes/module.ts
app/scripts/mutations/module.ts
app/scripts/mutations/mutations.controllers.ts

mutation page, cancer distribution and consquences

---

app/react-components/Mutation.js

mutation page: symbol in consquence table back to gene

---

app/react-components/Project.js
app/react-components/charts/BarChart.js
app/react-components/components/EntityPageHorizontalTable.js
app/react-components/components/SurvivalPlot.js
app/react-components/components/SurvivalPlotWrapper.js
app/scripts/projects/module.ts
app/scripts/projects/projects.controller.ts
app/styles/project.less
package.json

:sparkles: [PRTL-376] embed survival plot on project page

---

app/scripts/projects/module.ts

- so the rest of the project page loads at least

:bug: error handle survival plot fetch fail

---

app/scripts/app.ts
app/scripts/components/downloader/downloader.directive.ts
app/scripts/core/core.controller.ts
app/scripts/core/templates/generic-warning.html
app/scripts/core/templates/internal-server-error.html

- remove 'accept certificate' message
- always link gdc support in error modals
Closes #295

feat(app): PRTL-295 update error messages

---

app/react-components/index.js
package.json

IE wont load because window.location.pathname.includes does not exist.

polyfills for IE

---

app/scripts/files/files.directives.ts
app/scripts/files/templates/bam-slicing.html

fix(files): PRTL-282 close bam modal on dl

---

app/react-components/Gene.js
app/react-components/components/EntityPageHorizontalTable.js
app/react-components/uikit/Tooltip.js
app/scripts/components/quick-search/quick-search.directives.ts

@alex-wilmer wrapping your global-tooltip as a react component like this...?

:sparkles: tooltip as react component

---

app/react-components/Gene.js
app/react-components/Projects.js
app/react-components/components/EntityPageHorizontalTable.js
app/react-components/uikit/Tooltip.js
app/scripts/components/quick-search/quick-search.directives.ts

:sparkles: [PRTL-378] add counts to proj list viz as subtitles

---

app/react-components/oncogrid/OncoGridWrapper.js
app/react-components/oncogrid/SelectOverlay.js
app/react-components/uikit/Overlay.js

[PRTL-416] style popup

---

app/react-components/Gene.js
app/react-components/Mutation.js
app/react-components/Project.js
app/react-components/charts/BarChart.js
app/react-components/theme/icons/BarChart.js
app/react-components/theme/icons/Book.js
app/react-components/theme/icons/Case.js
app/react-components/theme/icons/Down.js
app/react-components/theme/icons/Edit.js
app/react-components/theme/icons/File.js
app/react-components/theme/icons/Minus.js
app/react-components/theme/icons/Plus.js
app/react-components/theme/icons/Table.js
app/react-components/uikit/TogglableUl.js
app/scripts/mutations/mutations.controllers.ts

8-in-1: tweaks to gene, mutation, project pages

---

app/react-components/Projects.js
app/react-components/charts/DoubleRingChart.js

:sparkles: Make double ring chart

---

app/scripts/home/templates/home.html

@alex-wilmer let me know if there was another issue with IE11.

[PRTL-360] enable highlights in IE

---

app/react-components/Project.js
app/react-components/Projects.js
app/scripts/projects/module.ts
app/scripts/projects/projects.controller.ts

- change title text on projects stackedbarchart
- correct Most Frequently Mutated Genes project page with counts

:bug: [PRTL-458] correct unique-ssm counts query

---

app/react-components/Projects.js
app/react-components/charts/DoubleRingChart.js
app/react-components/charts/StackedBarChart.js
app/scripts/projects/projects.controller.ts

:sparkles: [PRTL-450] match chart colors

---

app/react-components/Home.js
app/scripts/app.ts
app/scripts/home/home.controllers.ts

requires https://github.com/NCI-GDC/gdcapi/pull/660

:sparkles: [PRTL-49] data_release info from /status

---

app/react-components/oncogrid/OncoGridWrapper.js
app/react-components/oncogrid/oncoGridParams.js

adds a little space around the oncogrid and the oncogrid legend (and fixes the tooltips on the grid)

:bug: fix oncogrid sizing and tooltips

---

app/react-components/.eslintrc
app/react-components/Gene.js
app/react-components/Mutation.js
app/react-components/components/ProteinLolliplot.js
app/react-components/theme/mixins.js
app/react-components/uikit/Dropdown.js
app/react-components/uikit/UnstyledButton.js
app/scripts/app.ts
package.json
yarn.lock

:bug: [PRTL-508] prevent user-select on drag
:art: lint ProteinLolliplot component

:arrow_up: lolliplot 0.4.1

---

app/react-components/components/FrequentlyMutatedGenes.js
app/react-components/components/SurvivalPlotWrapper.js
app/react-components/theme/mixins.js

I also decreased the size of the buttons.

:sparkles: [PRTL-513, PRTL-513] move legend, and font sizes

---

modules/node_modules/@ncigdc/components/Cohort/OncogridTab.js
modules/node_modules/@ncigdc/components/Oncogrid/OncogridWrapper.js
modules/node_modules/@ncigdc/components/Oncogrid/getQueries.js

based on https://github.com/NCI-GDC/portal-ui/pull/1217
relies on https://github.com/NCI-GDC/gdcapi/pull/678
and https://github.com/NCI-GDC/gdcapi/pull/609

Oncogrid api update

---

modules/node_modules/@ncigdc/components/Oncogrid/getQueries.js
modules/node_modules/@ncigdc/utils/filters/index.js

requires https://github.com/NCI-GDC/gdcapi/pull/685

Update oncogrid endpoints and fix query merging

---

modules/node_modules/@ncigdc/components/Case.js
modules/node_modules/@ncigdc/components/CountCard.js
modules/node_modules/@ncigdc/components/Gene.js
modules/node_modules/@ncigdc/components/Oncogrid/OncogridWrapper.js
modules/node_modules/@ncigdc/components/Project.js
modules/node_modules/@ncigdc/components/ProjectVisualizations.js
modules/node_modules/@ncigdc/components/SSM.js
modules/node_modules/@ncigdc/containers/CasePage.js
modules/node_modules/@ncigdc/containers/ProjectPage.js
modules/node_modules/@ncigdc/routes/CaseRoute.js
modules/node_modules/@ncigdc/routes/ProjectRoute.js
modules/node_modules/@ncigdc/theme/global.css
modules/node_modules/@ncigdc/uikit/Tabs.js
modules/node_modules/@ncigdc/utils/constants.js

♻️ get all data and links working on project page and case page

---

modules/node_modules/@ncigdc/components/LoginButton.js
modules/node_modules/@ncigdc/components/UserDropdown.js
modules/node_modules/@ncigdc/utils/ajax/index.js
modules/node_modules/webpack_entry/Portal.js
package.json

- correct login/logout paths on env
- dispatch login on load

:bug: make auth work on env

---

modules/node_modules/@ncigdc/components/GitHut.js
modules/node_modules/@ncigdc/containers/ProjectsPage.js
modules/node_modules/webpack_entry/index.html

PRTL-624 ✨ angular githut in react

---

modules/node_modules/@ncigdc/components/BAMSlicingButton.js
modules/node_modules/@ncigdc/components/BiospecimenCard.js
modules/node_modules/@ncigdc/components/Case.js
modules/node_modules/@ncigdc/components/ClinicalCard.js
modules/node_modules/@ncigdc/components/DownloadButton.js
modules/node_modules/@ncigdc/components/File.js
modules/node_modules/@ncigdc/components/Header.js
modules/node_modules/@ncigdc/components/LoginButton.js
modules/node_modules/@ncigdc/components/Modals/NoAccessModal.js
modules/node_modules/@ncigdc/components/Project.js
modules/node_modules/@ncigdc/components/UserDropdown.js
modules/node_modules/@ncigdc/containers/CasePage.js
modules/node_modules/@ncigdc/containers/ProjectPage.js
modules/node_modules/@ncigdc/dux/auth.js

✨[PRTL-638] entity page actions

---

modules/node_modules/@ncigdc/components/MutationTable.js

pencil emoji for copy-only changes

✏️ PRTL-687 reword Most Freq. Mutations Cols

---

modules/node_modules/@ncigdc/containers/CaseAggregations.js

Note that primary site will not load data. Need api changes maybe

Fix case aggregation facet field names

---

app/index.html
app/scripts/cart/cart.directives.ts
app/scripts/components/downloader/downloader.directive.ts
app/scripts/components/facets/templates/range-facet.html
app/scripts/components/header/header.controller.ts
app/scripts/components/header/templates/header.html
app/scripts/components/ui/search/templates/search-bar.html
app/scripts/core/templates/browser-check-warning.html
app/scripts/core/templates/internal-server-error.html
app/scripts/core/templates/login-failed-warning.html
app/scripts/core/templates/request-access-to-download-single.html
app/scripts/core/templates/request-access-to-download.html
app/scripts/core/templates/warning.html
app/scripts/files/templates/download-manifest-info.html
app/scripts/home/templates/home.html

🐛 [PRTL-517] Homepage - Broken site links to the documentation

---

modules/node_modules/@ncigdc/components/AddCaseFilesToCartButton.js
modules/node_modules/@ncigdc/components/DropDownButton.js
modules/node_modules/@ncigdc/containers/CaseTable.js
modules/node_modules/@ncigdc/containers/CaseTr.js
modules/node_modules/@ncigdc/dux/cart.js
modules/node_modules/@ncigdc/uikit/Dropdown.js
modules/node_modules/@ncigdc/uikit/withToggle.js
modules/node_modules/@ncigdc/utils/withFilters.js

@NCI-GDC/oicrdevs ready for review

✨ [PRTL-640] Add Case Files to Cart Button

---

modules/node_modules/@ncigdc/components/Gene.js
modules/node_modules/@ncigdc/components/GeneTable.js
modules/node_modules/@ncigdc/components/MutationTable.js
modules/node_modules/@ncigdc/components/SSM.js

- GeneTable
- MutationTable
- SSM

🐛 PRTL-700 tooltips in table headers

---

modules/node_modules/@ncigdc/components/BioTreeItem.js
modules/node_modules/@ncigdc/components/BioTreeView.js
modules/node_modules/@ncigdc/components/BiospecimenCard.js
modules/node_modules/@ncigdc/containers/CasePage.js
modules/node_modules/@ncigdc/utils/biotree.js

- GraphQL query update to get fields mentioned in spec
- Passing type of entity when it is selected

🐛 [PRTL-627]  Biospecimen details section update

---

modules/node_modules/@ncigdc/components/Case.js
modules/node_modules/@ncigdc/components/ProjectVisualizations.js

Project Entity page
Most Frequent Mutations and Most Frequently Mutated Genes now accounting for project id when making request
Case Entity Page
Most Frequent Mutations accounting for case id when making request

🐛PRTL-690 filter most frequent mutations by project

---

modules/node_modules/@ncigdc/components/Aggregations/RangeFacet.js

:bug: round down minDisplayed days to years conversion

---

modules/node_modules/@ncigdc/utils/survivalplot.js

Survival plot legend text changed

🐛 PRTL-661 Fix title casing of the Most Frequent Mutation table and Survival Plot legend

---

modules/node_modules/@ncigdc/components/MutationTable.js

Added missing numerators and denominators on Most Frequent Mutations table

🐛 PRTL 688 numerators denominators on MFM table

---

modules/node_modules/@ncigdc/components/Aggregations/SuggestionFacet.js
modules/node_modules/@ncigdc/containers/AnnotationAggregations.js
modules/node_modules/@ncigdc/containers/AnnotationsPage.js
modules/node_modules/@ncigdc/containers/CaseAggregations.js
modules/node_modules/@ncigdc/containers/FileAggregations.js
modules/node_modules/@ncigdc/containers/ProjectAggregations.js
modules/node_modules/@ncigdc/containers/ProjectsPage.js
modules/node_modules/@ncigdc/containers/RepositoryPage.js
modules/node_modules/@ncigdc/routes/AnnotationsRoute.js
modules/node_modules/@ncigdc/routes/ProjectsRoute.js
modules/node_modules/@ncigdc/routes/RepositoryRoute.js

re-enable autocomplete on facets

---

modules/node_modules/@ncigdc/components/Aggregations/TermAggregation.js
modules/node_modules/@ncigdc/components/FacetSelection.js
modules/node_modules/@ncigdc/containers/CaseAggregations.js
modules/node_modules/@ncigdc/containers/FileAggregations.js

@shanewilson You were right, it did turn out to be simpler to reuse stuff from CaseAggreagations and FileAggregations :)

✨ [PRTL-703] custom facets modal : allow filtering out facets that are not useful

---

data/schema.json
data/version.json
modules/node_modules/@ncigdc/components/SortTableButton.js
modules/node_modules/@ncigdc/containers/AnnotationTable.js
modules/node_modules/@ncigdc/containers/FileTable.js
modules/node_modules/@ncigdc/containers/ProjectTable.js
modules/node_modules/@ncigdc/routes/AnnotationsRoute.js
modules/node_modules/@ncigdc/routes/CartRoute.js
modules/node_modules/@ncigdc/routes/CaseRoute.js
modules/node_modules/@ncigdc/routes/CohortRoute.js
modules/node_modules/@ncigdc/routes/ProjectsRoute.js
modules/node_modules/@ncigdc/routes/RepositoryRoute.js
modules/node_modules/@ncigdc/routes/SmartSearchRoute.js
modules/node_modules/@ncigdc/routes/legacy/FilesRoute.js
modules/node_modules/@ncigdc/utils/uri/index.js
modules/node_modules/@ncigdc/utils/uri/types.js

requires https://github.com/NCI-GDC/gdcapi/pull/706.

Prtl 598 table sorting

---

modules/node_modules/@ncigdc/components/Charts/BarChart.js
modules/node_modules/@ncigdc/components/Charts/StackedBarChart.js
modules/node_modules/@ncigdc/components/FrequentMutations.js
modules/node_modules/@ncigdc/components/FrequentlyMutatedGenes.js
modules/node_modules/@ncigdc/components/FrequentlyMutatedGenesContainer.js
modules/node_modules/@ncigdc/components/Modals/BAMModal.js
modules/node_modules/@ncigdc/components/MostAffectedCases.js
modules/node_modules/@ncigdc/components/ProjectVisualizations.js
modules/node_modules/@ncigdc/components/ProjectsCharts.js

- change href prop on BarChart to onClick handler instead

:bug: PRTL-717, PRTL-684 fix BarChart links

---

modules/node_modules/@ncigdc/components/FrequentMutations.js
modules/node_modules/@ncigdc/utils/survivalplot.js

Legend change. 
Link to mutation entity page from bar chart updated

🐛 [PRTL-769] Survival plot legend change

---

modules/node_modules/@ncigdc/components/QuickSearch/QuickSearch.js

💄enlarge quicksearch box

---

modules/node_modules/@ncigdc/components/SurvivalPlotWrapper.js
modules/node_modules/@ncigdc/utils/survivalplot.js

- don't show S1 label when only one curve
- spaces and dashes in legend

:bug: PRTL-790, PRTL-791 SurvivalPlot small tweaks

---

modules/node_modules/@ncigdc/containers/CaseTr.js
modules/node_modules/@ncigdc/utils/data/index.js

:bug: [PRTL-745] Case table - # Files is incorrect

---

modules/node_modules/@ncigdc/components/Aggregations/DateFacet.js
modules/node_modules/@ncigdc/components/Aggregations/ExactMatchFacet.js
modules/node_modules/@ncigdc/components/Aggregations/SuggestionFacet.js
modules/node_modules/@ncigdc/components/Aggregations/index.js
modules/node_modules/@ncigdc/components/FacetWrapper.js
modules/node_modules/@ncigdc/containers/AnnotationAggregations.js
modules/node_modules/@ncigdc/containers/CaseAggregations.js
modules/node_modules/@ncigdc/containers/FileAggregations.js
modules/node_modules/@ncigdc/containers/ProjectAggregations.js

:bug: PRTL-765 Annotations pg: add exact match facets entity_id & case_id

---

modules/node_modules/@ncigdc/components/FrequentMutations.js
modules/node_modules/@ncigdc/components/Gene.js
modules/node_modules/@ncigdc/components/MutationTable.js
modules/node_modules/@ncigdc/components/SSM.js
modules/node_modules/@ncigdc/containers/SSMPage.js
modules/node_modules/@ncigdc/utils/survivalplot.js

Truncating Mutation ID to 8 characters to the places mentioned in [specs](https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=GDCSPECS&title=Plan+B+-+Use+shortened+Mutation+ID%2C+pending+short+SSM+ID+availability)

[PRTL-757] Truncate Mutation ID to 8 characters 

---

modules/node_modules/@ncigdc/components/ClinicalCard.js
modules/node_modules/@ncigdc/containers/CasePage.js

Added `exposure` to the GraphQL query

PRTL-722 Missing Exposure Information

---

modules/node_modules/@ncigdc/components/MostAffectedCases.js

Added a check to see if demographic information exist otherwise pass an empty string

[PRTL-796] TCGA-CHOL not showing case information

---

modules/node_modules/@ncigdc/components/CancerDistribution.js
modules/node_modules/@ncigdc/components/FrequentlyMutatedGenes.js
modules/node_modules/@ncigdc/components/MostAffectedCases.js
modules/node_modules/@ncigdc/components/ProjectVisualizations.js
modules/node_modules/@ncigdc/containers/FrequentMutationsChart.js

- Making Bar charts half the width and aligning them left side

:bug: [PRTL-799] align bar chart left

---

modules/node_modules/@ncigdc/components/SSM.js

~wip, waiting for https://github.com/oncojs/lolliplot/pull/37 to be deployed~

🐛 [PRTL-829] hide links if there is no content

---

data/schema.json
data/version.json
modules/node_modules/@ncigdc/containers/CartPage.js

needs https://github.com/NCI-GDC/gdcapi/pull/715

:sparkles: PRTL-768 cart - add back file counts by project

---

modules/node_modules/@ncigdc/components/Pagination/__tests__/pagination.tests.js
modules/node_modules/@ncigdc/components/Pagination/index.js
modules/node_modules/@ncigdc/uikit/Pagination.js

✅🐛💄 PRTL-748 fix pagination range off by one

---

modules/node_modules/@ncigdc/components/Gene.js
modules/node_modules/@ncigdc/containers/FrequentMutationsTable.js

New prop to decide either to show gene symbol or not

🐛 [PRTL-830] Remove Gene Symbol from Gene page's mutation table

---

modules/node_modules/@ncigdc/components/MetadataDownloadButton.js

🐛 [PRTL-826] download metadata fix

---

modules/node_modules/@ncigdc/dux/__tests__/cart.tests.js
modules/node_modules/@ncigdc/dux/cart.js
modules/node_modules/@ncigdc/uikit/Notification.js

✅🐛 PRTL-778 enforce cart limit in all cart action creators

---

modules/node_modules/webpack_entry/index.html

Contain's compiled gql parser fix to handle <= number

🐛  PRTL-283 update gql language bundle

---

modules/node_modules/@ncigdc/components/AddCaseFilesToCartButton.js
modules/node_modules/@ncigdc/containers/CaseTr.js

Test procedure:
- Go to repository page
- Add a few file filters
- Click on add-to-cart button on a case row
- See "Add filtered Case files to the Cart (XX)" (this number may or may not be different from the "all Case files" depending on whether the filter applies)
http://142.1.177.119:32891/repository?facetTab=files&filters=~%28op~%27and~content~%28~%28op~%27in~content~%28field~%27files.data_category~value~%28~%27Raw%2A20Sequencing%2A20Data%29%29%29%29%29&searchTableTab=cases

🐛✨PRTL-770 add filtered case files to cart

---

modules/node_modules/@ncigdc/utils/generated-relay-query-parts/generate-script.js
modules/node_modules/@ncigdc/utils/generated-relay-query-parts/repositoryCaseAggregations.js
modules/node_modules/@ncigdc/utils/generated-relay-query-parts/repositoryFileAggregations.js
modules/node_modules/@ncigdc/utils/getFacetType.js

Using graphql data to generate fragments

🐛 PRTL-742 make primary site show up in facet sidebar

---

modules/node_modules/@ncigdc/containers/CaseTable.js

Change from `Cases` to `Files`

[PRTL-853] wrong header case table

---

modules/node_modules/@ncigdc/components/CurrentFilters.js

:sparkles: PRTL-845 CurrentFilters expands/hides with ...Less

---

modules/node_modules/@ncigdc/components/Layouts/FullWidthLayout.js

JIRA:
https://jira.opensciencedatacloud.org/browse/PRTL-810
Test:
Go to an entity page, e.g.
http://localhost:8080/projects/TCGA-CHOL
See that pages are no longer stretched

💄PRTL-810 add maximum width to entity page layout to avoid stretching

---

modules/node_modules/@ncigdc/components/BioTreeItem.js
modules/node_modules/@ncigdc/components/GitHut.js
modules/node_modules/webpack_entry/index.html

~wip~
Fixes for getting collab to load in IE11

🐛 move d3-tip script inside bundle to ensure load order

---

modules/node_modules/@ncigdc/containers/CancerDistributionChart.js

Bug fix for Cancer Distribution chart to align it on the left hand side.

[PRTL-866] Histogram not left aligned

---

modules/node_modules/@ncigdc/components/AddCaseFilesToCartButton.js
modules/node_modules/@ncigdc/components/AddToCartButtonAll.js
modules/node_modules/@ncigdc/components/AddToCartButtonSingle.js
modules/node_modules/@ncigdc/components/Case.js
modules/node_modules/@ncigdc/components/File.js
modules/node_modules/@ncigdc/components/Legacy/Nav.js
modules/node_modules/@ncigdc/components/Project.js
modules/node_modules/@ncigdc/theme/icons/ShoppingCart.js

- make ShoppingCart, File, Annotation icons consistent

:lipstick: PRTL-771, PRTL-724 case page icons

---

modules/node_modules/@ncigdc/components/Home.js

Added correct filter field value

🐛 [PRTL-880] Project primary site not selected by default

---

modules/node_modules/@ncigdc/components/SurvivalPlotWrapper.js
modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesTable.js

addresses https://jira.opensciencedatacloud.org/browse/PRTL-809 and https://jira.opensciencedatacloud.org/browse/PRTL-808

Survivalplot updates

---

modules/node_modules/@ncigdc/components/BiospecimenCard.js
modules/node_modules/@ncigdc/components/ClinicalCard.js
modules/node_modules/@ncigdc/components/File.js
modules/node_modules/@ncigdc/components/TableActions.js
modules/node_modules/@ncigdc/containers/AnnotationTable.js
modules/node_modules/@ncigdc/containers/CaseTable.js
modules/node_modules/@ncigdc/containers/FileTable.js
modules/node_modules/@ncigdc/containers/ProjectTable.js
modules/node_modules/@ncigdc/containers/cohort/CaseTable.js

I also updated a couple of API uses... sorry...

🐛 [PRTL-825] update button styles

---

.travis.yml

~this might fix yarn failing~
~it did not~
now it did

🐛 try to lock down yarn version by overwriting travis version

---

modules/node_modules/@ncigdc/components/QuickSearch/QuickSearchResults.js
package.json
yarn.lock

Depends on this API PR: https://github.com/NCI-GDC/gdcapi/pull/734
Test:
Quicksearch:  
| Search for | See |
| -----------| ----|
| BRAF | ![image](https://cloud.githubusercontent.com/assets/743976/24267314/45c3b838-0fe0-11e7-952c-321aa6622cd7.png)|
|ENSG00000157764|![image](https://cloud.githubusercontent.com/assets/743976/24267282/2eda7116-0fe0-11e7-8b43-653fd63acd0f.png)|
|92b75ae1-8d4d-52c2-8658-9c981eef0e57|![image](https://cloud.githubusercontent.com/assets/743976/24267331/551c9232-0fe0-11e7-850d-1c7e3eb3fdb7.png)|
|chr7:g.140753336A>T|![image](https://cloud.githubusercontent.com/assets/743976/24267260/2188a690-0fe0-11e7-9a8e-500e6c640be1.png)|
|V600E|![image](https://cloud.githubusercontent.com/assets/743976/24267226/0ad7d1a0-0fe0-11e7-83a6-acba9e3f7619.png)|

✨♻️ [PRTL-868] Improve quicksearch results

---

modules/node_modules/@ncigdc/components/CancerDistribution.js
modules/node_modules/@ncigdc/containers/CancerDistributionChart.js
modules/node_modules/@ncigdc/containers/FrequentMutationsChart.js
modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesChart.js
modules/node_modules/@ncigdc/containers/MostAffectedCasesChart.js

Have confirmed that we indeed want to remove bar width scaling based on number of bars 
https://oicr-gdc.slack.com/archives/C0H0726P7/p1490623679788124

PRTL-902 Set height of cancer distribution histogram to 300. Remove bar width scaling

---

modules/node_modules/@ncigdc/components/Case.js
modules/node_modules/@ncigdc/components/Project.js
modules/node_modules/@ncigdc/containers/CasePage.js
modules/node_modules/@ncigdc/containers/ProjectPage.js
modules/node_modules/@ncigdc/routes/CaseRoute.js
modules/node_modules/@ncigdc/routes/ProjectRoute.js

depends on https://github.com/NCI-GDC/gdcapi/pull/741

✨ [PRTL-907] hide viz when ssm_tested isn't true

---

modules/node_modules/@ncigdc/components/CurrentFilters.js
modules/node_modules/@ncigdc/components/SearchPage.js
modules/node_modules/@ncigdc/containers/ProjectsPage.js
modules/node_modules/@ncigdc/containers/legacy/FilesPage.js
modules/node_modules/@ncigdc/uikit/Button.js

"Open Query in Repository Page" button in the Project List page would open the query in Repository page.

[PRTL-756] Open query in repo page

---

modules/node_modules/@ncigdc/containers/SmartSearchPage.js

depends on https://github.com/NCI-GDC/gdcapi/pull/739

🐛 [PRTL-914] fix AS filters

---

modules/node_modules/@ncigdc/containers/FrequentMutationsTable.js

🐛 PRTL-942 update logic for choosing transcript

---

modules/node_modules/@ncigdc/components/Layouts/FullWidthLayout.js
modules/node_modules/@ncigdc/components/Pagination/Sizes.js
modules/node_modules/@ncigdc/containers/MostAffectedCasesTable.js
modules/node_modules/@ncigdc/containers/MutationsCount.js

~changing this to one query per row~

:sparkles: MostAffectedCaseTable - # mutations col

---

.eslintrc

proposed change to make some rules warnings instead of errors to make it a little clearer.

Eslint rules update

---

modules/node_modules/@ncigdc/components/Project.js
modules/node_modules/@ncigdc/components/ProjectVisualizations.js
modules/node_modules/@ncigdc/containers/ProjectPage.js
modules/node_modules/@ncigdc/routes/ProjectRoute.js

~requires `exposures` to be changed to nested in the case centric index mapping~
also depends on https://github.com/NCI-GDC/gdcapi/pull/739

🐛 [PRTL-912] uncomment filters now that api supports them

---

data/schema.json
data/version.json
modules/node_modules/@ncigdc/components/QuickSearch/QuickSearch.js
modules/node_modules/@ncigdc/components/QuickSearch/QuickSearchResults.js
modules/node_modules/@ncigdc/utils/getIconClassNameByEntityType.js
package.json

- still hits `/all`
- first step moving over the graphql

:recycle: PRTL-867 updates quicksearch to handle graphql response

---

modules/node_modules/@ncigdc/components/ProjectsCharts.js

💄 improve pie chart gradiation

---

modules/node_modules/@ncigdc/components/GitHut.js
modules/node_modules/@ncigdc/containers/SmartSearchPage.js

http://deploybot.gdc.cheapsteak.net:33315/projects?projectsTableTab=graph

🐛 manual angular DI minification protection

---

modules/node_modules/@ncigdc/components/ProjectsCharts.js

✨ PRTL-958 bump gene-limit of graph above project list page to 20

---

modules/node_modules/@ncigdc/containers/cohort/CaseTr.js

✨ Make Cohort Page Case Table Project ID link to Project page

---

modules/node_modules/@ncigdc/components/FacetWrapper.js
modules/node_modules/@ncigdc/components/SearchPage.js
modules/node_modules/@ncigdc/containers/cohort/GeneAggregations.js
modules/node_modules/@ncigdc/containers/cohort/SSMAggregations.js

♻️💄PRTL-919 Titles on Exploration Page Facets - Mutations + Genes Tab

---

modules/node_modules/@ncigdc/components/ExploringLinks.js
modules/node_modules/@ncigdc/components/Header.js

This reverts commit c21f0dede1081dee5285f34bbf0f9735bb94abd0.
low chance of regression

Revert "✨ "exploration" links, home/nav"

---

modules/node_modules/@ncigdc/components/SSM.js

this should fix item 6 in the spreadsheet

🐛 guard against null ssm.cosmic_id

---

modules/node_modules/@ncigdc/components/Case.js

http://localhost:8080/cases/dcd5860c-7e3a-44f3-a732-fe92fe3fe300

🐛PRTL-970 fix most frequent mutations numerator only showing 1

---

modules/node_modules/@ncigdc/containers/cohort/CohortPage.js
modules/node_modules/@ncigdc/containers/cohort/GeneAggregations.js
modules/node_modules/@ncigdc/containers/cohort/SSMAggregations.js

✨ PRTL-1001 cohort page id autocomplete

---

modules/node_modules/@ncigdc/components/ProjectVisualizations.js
modules/node_modules/@ncigdc/containers/FrequentMutationsChart.js
modules/node_modules/@ncigdc/containers/FrequentMutationsTable.js
modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesChart.js
modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesTable.js
modules/node_modules/@ncigdc/containers/MostAffectedCasesChart.js
modules/node_modules/@ncigdc/containers/MostAffectedCasesTable.js

https://jira.opensciencedatacloud.org/browse/PRTL-999

🐛 PRTL-999 Entity page charts and tables should update when changing projects without leaving container

---

modules/node_modules/@ncigdc/components/DownloadVisualizationButton.js
modules/node_modules/@ncigdc/components/Oncogrid/OncogridWrapper.js
modules/node_modules/@ncigdc/components/Oncogrid/oncoGridParams.js
modules/node_modules/@ncigdc/components/Oncogrid/tracks.js
modules/node_modules/@ncigdc/components/SurvivalPlotWrapper.js
modules/node_modules/@ncigdc/components/survivalPlot.css
modules/node_modules/@ncigdc/containers/CancerDistributionChart.js
modules/node_modules/@ncigdc/containers/FrequentMutationsChart.js
modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesChart.js
modules/node_modules/@ncigdc/containers/Lolliplot.js
modules/node_modules/@ncigdc/utils/supportsSvgToPng.js
modules/node_modules/@ncigdc/utils/wrapSvg.js
package.json
yarn.lock

Updates for svg download

---

modules/node_modules/@ncigdc/components/ProjectVisualizations.js
modules/node_modules/@ncigdc/containers/FrequentMutationsTable.js
modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesTable.js
modules/node_modules/@ncigdc/utils/survivalplot.js

🔧 PRTL-1021 survival plot, pass in 2000 on project page

---

modules/node_modules/@ncigdc/containers/GenePage.js
modules/node_modules/@ncigdc/containers/Lolliplot.js
modules/node_modules/@ncigdc/utils/data/index.js
modules/node_modules/@ncigdc/utils/groupByType.js
package.json
yarn.lock

React lolliplot

---

modules/node_modules/@ncigdc/containers/cohort/CaseTr.js

the ticket was completed here https://github.com/NCI-GDC/portal-ui/commit/5866c0337f7172d3f5c23c03bf2638d78206a12b already but the table headers were mismatched

:bug: PRTL-1023 correct CaseTable header

---

modules/node_modules/@ncigdc/components/HomeSearch.js

Update example copy to "e.g. BRAF, Breast, TCGA-BLCA, c0892598-1f7b-4f23-9cd8-731f797753d5"

✏️ PRTL-1030 update example copy

---

modules/node_modules/@ncigdc/containers/FrequentMutationsTable.js
modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesTable.js
modules/node_modules/@ncigdc/containers/GeneProjectBreakdown.js
modules/node_modules/@ncigdc/containers/MutationsCount.js

Figured it was better to make something we'll end up keeping

💄 column widths, toLocalString, survival button style

---

modules/node_modules/@ncigdc/containers/FrequentMutationsChart.js
modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesChart.js

:lipstick: PRTL-1037 fix barchart flexbox

---

package.json
yarn.lock

⬆️ react-lolliplot@0.6.3 fixes innacurate y values

---

modules/node_modules/@ncigdc/components/HomeSearch.js
modules/node_modules/@ncigdc/components/QuickSearch/QuickSearch.js
modules/node_modules/@ncigdc/utils/namespace.js
modules/node_modules/@ncigdc/utils/withSearch.js

Depends on https://github.com/NCI-GDC/portal-ui/pull/1508

🐛♻️PRTL-1031 fix issue with not being able to select using homepage input box

---

modules/node_modules/@ncigdc/components/Home.js
modules/node_modules/@ncigdc/components/HomeSearch.js
modules/node_modules/@ncigdc/components/QuickSearch/QuickSearch.js
modules/node_modules/@ncigdc/components/QuickSearch/QuickSearchResults.js
modules/node_modules/@ncigdc/utils/namespace.js
modules/node_modules/@ncigdc/utils/withSearch.js

Uses namespacing solution found by Jeff and discussed here https://github.com/acdlite/recompose/issues/358

✨ PRTL-1024 PRTL-1031 Add quicksearch to home page 

---

modules/node_modules/@ncigdc/components/Footer.js

this allows copying the hash and using chrome to search for the hash in the commit list

✨ update length of git hash display to match github

---

modules/node_modules/@ncigdc/components/Oncogrid/OncogridWrapper.js

:lipstick: PRTL-823 oncogrid switch fullscreen icon

---

modules/node_modules/@ncigdc/components/Aggregations/SuggestionFacet.js
modules/node_modules/@ncigdc/components/FacetSelection.js
modules/node_modules/@ncigdc/components/HomeSearch.js
modules/node_modules/@ncigdc/components/QuickSearch/QuickSearch.js
modules/node_modules/@ncigdc/containers/AnnotationsPage.js
modules/node_modules/@ncigdc/containers/ProjectsPage.js
modules/node_modules/@ncigdc/containers/cohort/CohortPage.js
modules/node_modules/@ncigdc/utils/namespace.js
modules/node_modules/@ncigdc/utils/withSearch.js
modules/node_modules/@ncigdc/utils/withSelectableList.js

Added new HoC `withSelectableList` which is now used in QuickSearch, HomeSearch, SuggestionFacet, FacetSelection, and can be used anywhere where keyboard navigation on a list is desired
Also added loading message to SuggestionFacet so it'll say Loading when there are no items and is waiting for a request to come back.

✨♻️ PRTL-969 allow keyboard selection with facet suggestions, add loading message

---

modules/node_modules/@ncigdc/components/SurvivalPlotWrapper.js
modules/node_modules/@ncigdc/components/VisualizationHeader.js
modules/node_modules/@ncigdc/containers/CancerDistributionChart.js
modules/node_modules/@ncigdc/containers/FrequentMutationsChart.js
modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesChart.js
modules/node_modules/@ncigdc/containers/MostAffectedCasesChart.js
modules/node_modules/@ncigdc/theme/mixins.js
modules/node_modules/@ncigdc/uikit/Flex/Row.js
modules/node_modules/@ncigdc/uikit/Loaders/Loader.js

adding `&w=1` will cut this diff in half :)

Prtl 938 vertical space

---

modules/node_modules/@ncigdc/components/Charts/BarChart.js
modules/node_modules/@ncigdc/components/Charts/StackedBarChart.js
modules/node_modules/@ncigdc/components/survivalPlot.css
modules/node_modules/@ncigdc/containers/FrequentMutationsChart.js
modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesChart.js
modules/node_modules/@ncigdc/containers/MostAffectedCasesChart.js

:lipstick: PRTL-850 bold x/y labels and increase font size

---

modules/node_modules/@ncigdc/components/ProjectsCharts.js
modules/node_modules/@ncigdc/containers/GeneProjectBreakdown.js
modules/node_modules/@ncigdc/utils/filters/prepared/caseHasMutation.js

🐛 PRTL-1079 use graphql filtered case totals to display total unique cases in stacked graph title

---

modules/node_modules/@ncigdc/components/ProjectsCharts.js

Prtl 1060 update filtering criteria to find top genes

---

modules/node_modules/@ncigdc/components/FacetSelection.js
modules/node_modules/@ncigdc/components/FacetWrapper.js
modules/node_modules/@ncigdc/containers/cohort/CaseAggregations.js
modules/node_modules/@ncigdc/utils/withFacetSelection.js

- fix usefulFacets check to not include aggregations is null
- add validFacetPrefixes array to check during facetExclusionTest

:sparkles: PRTL-920 Cohort add custom facets

---

modules/node_modules/@ncigdc/uikit/TogglableUl.js

jsx/a11y complains about li not being semantically clickable.. wrap the `li` contents with something that is?

🐛 fix toggle callback in ToggleableUI

---

modules/node_modules/@ncigdc/components/Links/CohortLink.js
modules/node_modules/@ncigdc/components/Oncogrid/OncogridWrapper.js
modules/node_modules/@ncigdc/containers/CancerDistributionTable.js
modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesTable.js
modules/node_modules/@ncigdc/containers/MostAffectedCasesTable.js
modules/node_modules/@ncigdc/containers/MutationsCount.js
modules/node_modules/@ncigdc/containers/ProjectBreakdown.js
modules/node_modules/@ncigdc/containers/cohort/CaseTr.js

~wip~
replaces https://github.com/NCI-GDC/portal-ui/pull/1497
Links are disabled, to enable merge https://github.com/NCI-GDC/portal-ui/pull/1567

Add Explore links

---

modules/node_modules/@ncigdc/containers/CancerDistributionTable.js

✏️ PRTL-1103 column title changes

---

modules/node_modules/@ncigdc/components/GitHut.js

💄PRTL-1084 center githut title

---

modules/node_modules/@ncigdc/containers/MostAffectedCasesTable.js
modules/node_modules/@ncigdc/containers/cohort/CaseTable.js
modules/node_modules/@ncigdc/containers/cohort/CaseTr.js

- remove available_variation_data is ssm from `CohortLink`s
- update tooltips

:bug: PRTL-1102 MACTable: update links and tooltips

---

modules/node_modules/@ncigdc/containers/FileTable.js

related resource: 
https://github.com/dequelabs/axe-core/blob/ad46dd506c8134d02717fc8975f615794f03f492/test/checks/tables/th-has-data-cells.js
fixes `th-has-data-cells` error

✅♿️ PRTL-1092 remove "Action" from cart page file table

---

modules/node_modules/@ncigdc/components/Aggregations/FacetHeader.js
modules/node_modules/@ncigdc/components/Aggregations/SuggestionFacet.js
modules/node_modules/@ncigdc/components/Aggregations/TermAggregation.js
modules/node_modules/@ncigdc/components/Annotation.js
modules/node_modules/@ncigdc/components/Case.js
modules/node_modules/@ncigdc/components/FacetSelection.js
modules/node_modules/@ncigdc/components/File.js
modules/node_modules/@ncigdc/components/GDCAppsDropdown.js
modules/node_modules/@ncigdc/components/GDCAppsRow.js
modules/node_modules/@ncigdc/components/Header.js
modules/node_modules/@ncigdc/components/HomeSearch.js
modules/node_modules/@ncigdc/components/Links/utils.js
modules/node_modules/@ncigdc/containers/AnnotationTr.js
modules/node_modules/@ncigdc/containers/CancerDistributionTable.js
modules/node_modules/@ncigdc/containers/CaseTr.js
modules/node_modules/@ncigdc/containers/ConsequencesTable.js
modules/node_modules/@ncigdc/containers/FileTr.js
modules/node_modules/@ncigdc/containers/FrequentMutationsTable.js
modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesTable.js
modules/node_modules/@ncigdc/containers/MostAffectedCasesTable.js
modules/node_modules/@ncigdc/containers/ProjectTr.js
modules/node_modules/@ncigdc/containers/cohort/CaseTr.js

:wheelchair: 508

---

modules/node_modules/@ncigdc/containers/cohort/CaseAggregations.js

minor changes to placeholder text only.

:bug: PRTL-1117 Cohort case id/case submitter id tweaks

---

modules/node_modules/webpack_entry/Root.js

It was appending another hash for every retry so you'd end up with
`url?hash=value?hash=value`

🐛 only append hash to url once

---

modules/node_modules/@ncigdc/containers/CaseAggregations.js
modules/node_modules/@ncigdc/containers/FileAggregations.js
modules/node_modules/@ncigdc/containers/__test__/CaseAggregation.test.js
modules/node_modules/@ncigdc/containers/cohort/CaseAggregations.js

🐛🐎 - Fix: unslow repo page

---

modules/node_modules/@ncigdc/components/NoResultsMessage.js
modules/node_modules/@ncigdc/components/SummaryCard.js
modules/node_modules/@ncigdc/containers/CaseTr.js
modules/node_modules/@ncigdc/containers/RepositoryPage.js
modules/node_modules/@ncigdc/containers/cohort/CohortPage.js

✨ PRTL-1125 no results msgs

---

modules/node_modules/@ncigdc/components/TabPieCharts/ExploreCasesPies.js
modules/node_modules/@ncigdc/containers/explore/CaseAggregations.js
modules/node_modules/@ncigdc/containers/explore/CaseTable.js
modules/node_modules/@ncigdc/containers/explore/CaseTr.js
modules/node_modules/@ncigdc/containers/explore/ExplorePage.js
modules/node_modules/@ncigdc/utils/generated-relay-query-parts/exploreCaseAggregations.js
modules/node_modules/@ncigdc/utils/generated-relay-query-parts/generate-script.js
modules/node_modules/@ncigdc/utils/generated-relay-query-parts/index.js
modules/node_modules/@ncigdc/utils/generated-relay-query-parts/repositoryCaseAggregations.js
modules/node_modules/@ncigdc/utils/generated-relay-query-parts/repositoryFileAggregations.js
modules/node_modules/@ncigdc/utils/getFacetType.js

huge PR because generated script for explore facets

🐛 exploration page cohort -> explore updates

---

modules/node_modules/@ncigdc/components/Aggregations/SuggestionFacet.js

🐛 fixes warning about unknown attribute ariaOwns (1 LOC)

---

package.json

note: the schema is for relay's babel transform (i think)

add npm script to clear cache

---

modules/node_modules/@ncigdc/components/Footer.js

✨ [PRTL-1148] add release info in footer

---

modules/node_modules/@ncigdc/containers/GenePage.js

💄 nicer look for "no protein coding" in lolliplot

---

modules/node_modules/@ncigdc/components/ClinicalCard.js

- follow up typo
- remove Alcohol Intensity row

PRTL-1144 Case clinical section tweaks

---

modules/node_modules/@ncigdc/components/Oncogrid/getQueries.js

filter by case_ids and some simple chunking if it's over 1000

🐛 quick fix to get all occurrences for oncogrid

---

modules/node_modules/@ncigdc/utils/survivalplot.js

- so that the mutated curve is orange

🎨 PRTL-1058 flip mutated and not mutated  survival curves

---

modules/node_modules/@ncigdc/components/Header.js

🎛PRTL-1162 Remove analysis menu from menu bar

---

modules/node_modules/@ncigdc/components/CurrentFilters.js
modules/node_modules/@ncigdc/containers/RepositoryPage.js
modules/node_modules/@ncigdc/theme/icons/Case.js
modules/node_modules/@ncigdc/theme/icons/File.js
modules/node_modules/@ncigdc/theme/icons/Save.js
modules/node_modules/@ncigdc/theme/icons/index.js

✨ [PRTL-988] add summary bar

---

modules/node_modules/@ncigdc/components/CartDownloadDropdown.js
modules/node_modules/@ncigdc/components/Modals/NoAccessModal.js
modules/node_modules/@ncigdc/containers/CartPage.js

Fix cart page, added cancel text on download cart model

PRTL-1004 rename accept button when downloading cart

---

modules/node_modules/@ncigdc/containers/CancerDistributionChart.js
modules/node_modules/@ncigdc/containers/FrequentMutationsChart.js
modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesChart.js
modules/node_modules/@ncigdc/containers/MostAffectedCasesChart.js

~~Should we filter out `"__dataID__":`s from the 'Download JSON'? The other viz JSON downloads have them in too.~~

PRTL-1000 add download button to mac chart

---

modules/node_modules/@ncigdc/containers/CancerDistributionTable.js

Cherry picked commit from https://github.com/NCI-GDC/portal-ui/pull/1637

🐛PRTL-1173 add "Available Variation Data is SSM" to filters

---

modules/node_modules/@ncigdc/components/Case.js
modules/node_modules/@ncigdc/components/Explore/GenesTab.js
modules/node_modules/@ncigdc/components/Explore/MutationsTab.js
modules/node_modules/@ncigdc/components/ProjectVisualizations.js
modules/node_modules/@ncigdc/containers/FrequentMutationsTable.js
modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesTable.js
modules/node_modules/@ncigdc/containers/GenePage.js
modules/node_modules/@ncigdc/utils/survivalplot.js

Index now seems fast enough to not need a size limit for the survival graph
(The option is still there if we need it)

🎛 PRTL-1145 remove client side limit for survival graph

---

modules/node_modules/@ncigdc/components/Oncogrid/OncogridWrapper.js
modules/node_modules/@ncigdc/components/Oncogrid/dataMapping.js
modules/node_modules/@ncigdc/components/Oncogrid/getQueries.js
modules/node_modules/@ncigdc/components/ProjectVisualizations.js

✨ [PRTL-1131,  PRTL-1134] allow oncogrid to work with all impacts

---

modules/node_modules/@ncigdc/containers/CancerDistributionTable.js
modules/node_modules/@ncigdc/containers/FrequentMutationsTable.js
modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesTable.js
modules/node_modules/@ncigdc/containers/MostAffectedCasesTable.js
modules/node_modules/@ncigdc/containers/ProjectBreakdown.js
modules/node_modules/@ncigdc/containers/explore/CaseTable.js

🐛 update enabled links to use Explore
🐛 PRTL-1151 explore links updates
✨ special conditions for ssm variation
🐛 ssm tested in projectBreakdown link
🐛 ssm tested in projectBreakdown link
🐛 correct filter for mutation counts (fixes link)

✨ merge cohorlink queries, link ctx column mutation table

---

modules/node_modules/@ncigdc/components/Explore/GenesTab.js
modules/node_modules/@ncigdc/components/ProjectVisualizations.js
modules/node_modules/@ncigdc/containers/FrequentMutationsTable.js
modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesTable.js

Filters on page werent previously being passed into survivalplot api due to existence of project id

🐛♻️  PRTL-1074 survival total cases count off

---

modules/node_modules/@ncigdc/containers/GenePage.js
modules/node_modules/@ncigdc/containers/Lolliplot.js
modules/node_modules/@ncigdc/utils/data/index.js
package.json
yarn.lock

⬆️ react-lolliplot@0.8*

---

data/schema.json
data/version.json
modules/node_modules/@ncigdc/components/Oncogrid/OncogridWrapper.js
modules/node_modules/@ncigdc/components/Oncogrid/getQueries.js
modules/node_modules/@ncigdc/components/ProjectsCharts.js
modules/node_modules/@ncigdc/containers/Lolliplot.js
modules/node_modules/@ncigdc/utils/filters/prepared/significantConsequences.js

Also created a filter for the consequence types so it can be shared.
depends on https://github.com/NCI-GDC/gdcapi/pull/779

✨ [PRTL-1166] add consequence type filter to lolliplot

---

modules/node_modules/@ncigdc/components/Explore/GenesTab.js
modules/node_modules/@ncigdc/components/Explore/MutationsTab.js

https://jira.opensciencedatacloud.org/browse/PRTL-1177

🐛 PRTL-1177 remove comparison survival graph when filters change

---

modules/node_modules/@ncigdc/containers/CaseAggregations.js
modules/node_modules/@ncigdc/containers/FileAggregations.js
modules/node_modules/@ncigdc/containers/explore/CaseAggregations.js

Fixes problem with custom facets showing no data after being selected

🐛 PRTL-1109 facet shows no data

---

modules/node_modules/@ncigdc/components/Explore/GenesTab.js
modules/node_modules/@ncigdc/components/Explore/MutationsTab.js
modules/node_modules/@ncigdc/containers/FrequentMutationsChart.js
modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesChart.js

https://jira.opensciencedatacloud.org/browse/PRTL-1133

✨ PRTL-1133 Gene and Mutation bar graphs should have different behaviour based on context (Project or Exploration)

---

modules/node_modules/webpack_entry/index.js

~WIP~
requires a change to knit https://github.com/knitjs/knit/pull/55

🔥 remove hot module loading

---

modules/node_modules/@ncigdc/components/DownloadTableToTsvButton.js
modules/node_modules/@ncigdc/components/EntityPageHorizontalTable.js
modules/node_modules/@ncigdc/components/TableActions.js
modules/node_modules/@ncigdc/containers/AnnotationTable.js
modules/node_modules/@ncigdc/containers/AnnotationTr.js
modules/node_modules/@ncigdc/containers/CancerDistributionChart.js
modules/node_modules/@ncigdc/containers/CancerDistributionTable.js
modules/node_modules/@ncigdc/containers/CaseTable.js
modules/node_modules/@ncigdc/containers/CaseTr.js
modules/node_modules/@ncigdc/containers/FileTable.js
modules/node_modules/@ncigdc/containers/FrequentMutationsTable.js
modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesTable.js
modules/node_modules/@ncigdc/containers/MostAffectedCasesTable.js
modules/node_modules/@ncigdc/containers/ProjectBreakdown.js
modules/node_modules/@ncigdc/containers/ProjectTable.js
modules/node_modules/@ncigdc/containers/explore/CaseTable.js
modules/node_modules/@ncigdc/containers/explore/CaseTr.js
modules/node_modules/@ncigdc/utils/__tests__/toTsvString.test.js
modules/node_modules/@ncigdc/utils/toTsvString.js

~~[WIP]~~ Couldn't think of a better way to do this with `<ProjectBreakdown>` and `<MutationsCount>` both being self-contained relay Containers that make secondary calls. I'm not sure how to get the data out of them in the parent. Straight up using document.querySelector. Taking suggestions for better solutions.
done, ~~pending specs confirmation~~ also done!

:sparkles: PRTL-1187 export html table as tsv

---

modules/node_modules/@ncigdc/components/Oncogrid/dataMapping.js
modules/node_modules/@ncigdc/components/Oncogrid/getQueries.js
modules/node_modules/@ncigdc/components/Oncogrid/oncoGridParams.js

~WIP~
remove duplicate mutations from the oncogrid
Also reduces time to map occurrences from about 2700ms to 160ms

🐛 [PRTL-1206] fix duplicates in oncogrid

---

modules/node_modules/@ncigdc/components/TableActions.js
modules/node_modules/@ncigdc/containers/CancerDistributionTable.js
modules/node_modules/@ncigdc/containers/FrequentMutationsTable.js
modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesTable.js
modules/node_modules/@ncigdc/containers/MostAffectedCasesTable.js
modules/node_modules/@ncigdc/routes/GeneRoute.js
modules/node_modules/@ncigdc/theme/icons/index.js

Should be merged after ~https://github.com/NCI-GDC/portal-ui/pull/1666~ and https://github.com/NCI-GDC/gdcapi/pull/786

✨ [PRTL-1188] add table exports

---

modules/node_modules/@ncigdc/components/Explore/ExploreCasesCharts.js

primary site & disease type under explore case are populated now so update pie fields.

[minor] PRTL-1139 update primary site & disease type explore pies

---

modules/node_modules/@ncigdc/containers/CaseTable.js
modules/node_modules/@ncigdc/containers/explore/CaseTable.js
modules/node_modules/@ncigdc/containers/explore/ExplorePage.js

pass case_sort to query in explore container, fix primarsite field

[2 LOC!] PRTL-1123 fix explore cases sorting

---

modules/node_modules/@ncigdc/containers/FrequentMutationsChart.js
modules/node_modules/@ncigdc/containers/FrequentMutationsTable.js

requires https://github.com/NCI-GDC/gdcapi/pull/793

🐛 [PRTL-1169] sort most frequent mutations table and chart

---

modules/node_modules/@ncigdc/components/ProjectsCharts.js

requires https://github.com/NCI-GDC/gdcapi/pull/795

🐛 [PRTL-1214] pass filters to top_cases_counts_by_genes

---

modules/node_modules/@ncigdc/containers/Lolliplot.js

@alex-wilmer do you see any problems with this? It was making 4 requests when it should have been making 2 (might also be a problem with relay making the same request type, but this is a start :) )

🐛 prevent multiple calls for the same data

---

modules/node_modules/@ncigdc/components/Aggregations/NotMissingFacet.js
modules/node_modules/@ncigdc/containers/explore/ExplorePage.js
modules/node_modules/@ncigdc/containers/explore/SSMAggregations.js
modules/node_modules/@ncigdc/utils/__tests__/string.test.js
modules/node_modules/@ncigdc/utils/string.js

depends on https://github.com/NCI-GDC/gdcapi/pull/788

Feat/1208 external db facets as 'not missing' query

---

.vscode/launch.json

Mind if we add this? I don't have chrome installed with brew :)

🛠 add non brew chrome debugger for vscode

---

src/packages/@ncigdc/components/Case.js
src/packages/@ncigdc/components/Charts/BarChart.js
src/packages/@ncigdc/components/Explore/MutationsTab.js
src/packages/@ncigdc/components/ProjectVisualizations.js
src/packages/@ncigdc/components/SurvivalPlotWrapper.js
src/packages/@ncigdc/containers/CancerDistributionChart.js
src/packages/@ncigdc/containers/GenePage.js
src/packages/@ncigdc/containers/SSMPage.js
src/packages/@ncigdc/modern_components/AffectedCasesBarChart/AffectedCasesBarChart.js
src/packages/@ncigdc/modern_components/GenesBarChart/GenesBarChart.js
src/packages/@ncigdc/modern_components/SsmsBarChart/SsmsBarChart.js

Removes the bandwidth calculation in all the charts.
Also, cancer dist chart to show 20

♻️ [PRTL-1259] pass width instead of bandwidth

---

src/packages/@ncigdc/components/Header.js

- if the user state exists, then show session expired
- also forceLogout the user

🐛 PRTL-1274 401/403 check if logged in first b4 popup

---

src/packages/@ncigdc/components/Aggregations/FacetHeader.js
src/packages/@ncigdc/components/Aggregations/FacetResetButton.js
src/packages/@ncigdc/components/Aggregations/RangeFacet.js
src/packages/@ncigdc/components/CurrentFilters.js
src/packages/@ncigdc/utils/filters/index.js

note it's this grey rest button not the clear all:

:bug: PRTL-1270 Fix CurrentFilters number display, facet reset for range

---

package-lock.json
package.json

- fixes firefox incorrect zooming

⬆️ @oncojs/react-lolliplot@0.10.4

---

src/packages/@ncigdc/components/CartDownloadDropdown.js
src/packages/@ncigdc/components/File.js
src/packages/@ncigdc/containers/CartPage.js
src/packages/@ncigdc/dux/cart.js
src/packages/@ncigdc/utils/auth/index.js

deployed to nightly, looks to be working there

:bug: PRTL-1276 cart file permission fixes

---

src/Root.js
src/packages/@ncigdc/utils/retryMiddleware.js

Took a stab at making the retry middleware take the first successful response, seems to work.
Needs more testing/refactoring but thought I would be it here if anyone wants to take a look.

✨ retry middleware that takes the first successfull query

---

src/packages/@ncigdc/components/UserDropdown.js
src/packages/@ncigdc/utils/auth/__tests__/auth.test.js
src/packages/@ncigdc/utils/auth/index.js

- fix error that prevented dling token

🐛 PRTL-1295 nesting mistake in projects count

---

src/packages/@ncigdc/components/Modals/FirstTimeModal.js

didn't catch that one sentence changed 😨

✏️ 1243 update warning wording

---

src/packages/@ncigdc/uikit/Button.js

🐛 white btn hover color

---

package.json
src/packages/@ncigdc/components/Aggregations/RangeFacet.js
src/packages/@ncigdc/components/DismissibleBanner.js
src/packages/@ncigdc/components/Legacy/Header.js
src/packages/@ncigdc/components/UserDropdown.js

gdc.nci.nih.gov -> gdc.cancer.gov
gdc-portal.nci.nih.gov -> portal.gdc.cancer.gov
gdc-docs.nci.nih.gov -> docs.gdc.cancer.gov

SV-697 update links to use cancer.gov

---

src/packages/@ncigdc/dux/bannerNotification.js

🐛 fix dupe key for banner notification

---

src/packages/@ncigdc/uikit/Tooltip/GlobalTooltip.js

moveTooltip needs to wait to be called after tooltip's offsetHeight has the correct value

🐛 PRTL-838 tooltip positioning off in IE

---

public/index.html

Support compatibility mode by disabling compatibility mode

🐛 PRTL-1319 “support" compatibility mode

---

package-lock.json
package.json
src/packages/@ncigdc/components/Oncogrid/OncogridWrapper.js
src/packages/@ncigdc/components/Oncogrid/getQueries.js
src/packages/@ncigdc/components/Oncogrid/oncoGridParams.js

testing out https://github.com/oncojs/oncogrid/pull/34

⚡️⬆️ [PRTL-1340, PRTL-1339, PRTL-1341] speed up oncogrid

---

package-lock.json
package.json

relevant commits on survivaplot:
https://github.com/oncojs/survivalplot/commit/825462841ae096ea8b137b7239401e37226d0685
https://github.com/oncojs/survivalplot/commit/02ea028dedbc45f17757383b8eb21ee22b324be0
From: freezes indefinitely down to freezes ~10 seconds

Decrease cases rendered by survivalplot (base: master)

---

package.json
src/packages/@ncigdc/components/Oncogrid/sort.js

fix in https://github.com/oncojs/oncogrid/pull/34

🐛⬆️[PRTL-1373] fixes tracks not sorting

---

src/packages/@ncigdc/components/Pagination/index.js
src/packages/@ncigdc/tableModels/filesTableModel.js
src/packages/@ncigdc/theme/versions/active.js

- missing bgcolor in pagination
- right align filesize in filetable

small ui fixes

---

src/packages/@ncigdc/components/File.js
src/packages/@ncigdc/components/LocalPaginationTable.js
src/packages/@ncigdc/containers/CancerDistributionTable.js
src/packages/@ncigdc/routes/AnnotationRoute.js
src/packages/@ncigdc/routes/CaseRoute.js
src/packages/@ncigdc/routes/FileRoute.js
src/packages/@ncigdc/routes/GeneRoute.js
src/packages/@ncigdc/routes/ProjectRoute.js
src/packages/@ncigdc/routes/SSMRoute.js
src/packages/@ncigdc/routes/utils.js

Also fixes fixes routes remounting on query param update.

✨ [PRTL-936] add pagination to associated entities

---

src/packages/@ncigdc/components/Case.js
src/packages/@ncigdc/components/Project.js
src/packages/@ncigdc/components/SampleSize.js
src/packages/@ncigdc/components/SparkMeterWithTooltip.js
src/packages/@ncigdc/components/SummaryCard.js
src/packages/@ncigdc/containers/CartPage.js
src/packages/@ncigdc/uikit/SparkMeter.js
src/packages/@ncigdc/utils/filters/index.js

Add spark meters to Case, Project entity pages and Cart page

✨ PRTL-1494 Replace pie chart in summarycards with bar charts on Case, Project entity pages and Cart page

---

src/packages/@ncigdc/components/Project.js
src/packages/@ncigdc/containers/RepositoryPage.js

If https://github.com/NCI-GDC/gdcapi/pull/810 is merged, these fields do nothing.

🔥 remove fields from manifest download

---

src/packages/@ncigdc/components/Charts/StackedBarChart.js
src/packages/@ncigdc/components/ProjectsCharts.js

:sparkles: PRTL-1387 project bar axis toggle units

---

src/index.js
src/packages/@ncigdc/utils/trace.js

🔧 trace hoc

---

src/packages/@ncigdc/components/Annotation.js
src/packages/@ncigdc/components/Case.js
src/packages/@ncigdc/components/File.js
src/packages/@ncigdc/components/Project.js
src/packages/@ncigdc/containers/CancerDistributionTable.js
src/packages/@ncigdc/containers/CaseAggregations.js
src/packages/@ncigdc/containers/ProjectAggregations.js
src/packages/@ncigdc/containers/explore/CaseAggregations.js
src/packages/@ncigdc/modern_components/AffectedCasesBarChart/AffectedCasesBarChart.js
src/packages/@ncigdc/modern_components/AffectedCasesTable/AffectedCasesTable.js
src/packages/@ncigdc/tableModels/annotationsTableModel.js
src/packages/@ncigdc/tableModels/casesTableModel.js
src/packages/@ncigdc/tableModels/exploreCasesTableModel.js
src/packages/@ncigdc/tableModels/projectsTableModel.js

- Project ID -> Project
- Case Submitter ID -> Case ID
- Entity Submitter ID -> Entity ID
- add 'Project' in tooltip

:pencil: rename ID labels

---

package-lock.json
package.json
src/packages/@ncigdc/containers/SmartSearchPage.js

✨ PRTL-1444 use lodash-backports to register aliases of lodash v3 functions

---

src/packages/@ncigdc/modern_components/CreateSetButton/CreateExploreCaseSetButton.js

✏️PRTL-1443 rename button to "View Cases Files in Repository"

---

src/packages/@ncigdc/components/SurvivalPlotWrapper.js

requires https://github.com/NCI-GDC/gdcapi/pull/815

PRTL-1441 survival plot: use submitter id

---

src/packages/@ncigdc/components/DownloadButton.js
src/packages/@ncigdc/components/SortTableButton.js
src/packages/@ncigdc/uikit/Button.js

♻️ examples to set component name displayed in react dev tools

---

src/packages/@ncigdc/modern_components/environment.js

requires: https://github.com/NCI-GDC/gdcapi/pull/811
A common complaint is having to click on many `/graphql` tabs in the network tab to figure out which query is which. Relay Classic doesn't appear to allow renaming the query name (why??) but this is easier done with modern.

✨ put component name for post endpoint graphql

---

src/packages/@ncigdc/components/ArrangeColumns.js
src/packages/@ncigdc/containers/CasesTable.js
src/packages/@ncigdc/containers/FilesTable.js
src/packages/@ncigdc/containers/ProjectsTable.js
src/packages/@ncigdc/dux/tableColumns.js
src/packages/@ncigdc/modern_components/ExploreCasesTable/ExploreCasesTable.js

Quick fix for the arrange column dropdown order issue.

🐛 [PRTL-1281] maintain arrange column order

---

src/packages/@ncigdc/components/Oncogrid/OncogridWrapper.js

works not sure if best approach

:bug: PRTL-1449 hide oncogrid until render:all:end

---

src/packages/@ncigdc/modern_components/GenesTable/GenesTable.js

🐛 genestable overflow-x

---

src/packages/@ncigdc/components/LocationSubscriber.js
src/packages/@ncigdc/modern_components/ExploreCasesTable/ExploreCasesTable.js
src/packages/@ncigdc/utils/withRouter.js

react-router decided that withRouter shouldn't forceUpdate anymore, we rely on the url for state so I don't think this works for us without a refactor.

🐛 use withRouter that will forceUpdate children on location change

---

package-lock.json
package.json
src/packages/@ncigdc/components/Oncogrid/OncogridWrapper.js
src/packages/@ncigdc/components/Oncogrid/mouseEvents.js
src/packages/@ncigdc/components/Oncogrid/oncoGridParams.js
src/packages/@ncigdc/components/Oncogrid/oncogrid.css
src/packages/@ncigdc/components/Oncogrid/tracks.js

refactor for https://github.com/oncojs/oncogrid/pull/38

♻️  use events for tooltips

---

src/packages/@ncigdc/modern_components/Lolliplot/Lolliplot.js
src/packages/@ncigdc/modern_components/Lolliplot/LolliplotStats.js
src/packages/@ncigdc/modern_components/Lolliplot/LolliplotWrapper.js

Just for consistency, switching to use withSize.

♻️ use withSize in lolliplot

---

public/_redirects

66c6ae7 app.netlify.com/sites/rubber-tapper-lifts-72118/deploys/59974dc0a700c42f31d411c5

test ui deployments

---

data/schema.graphql
data/schema.json
src/packages/@ncigdc/modern_components/setButtons/RemoveFromExploreCaseSetButton.js
src/packages/@ncigdc/modern_components/setButtons/RemoveFromExploreGeneSetButton.js
src/packages/@ncigdc/modern_components/setButtons/RemoveFromRepositoryCaseSetButton.js
src/packages/@ncigdc/modern_components/setButtons/__generated__/RemoveFromExploreCaseSetButtonMutation.graphql.js
src/packages/@ncigdc/modern_components/setButtons/__generated__/RemoveFromExploreGeneSetButtonMutation.graphql.js
src/packages/@ncigdc/modern_components/setButtons/__generated__/RemoveFromRepositoryCaseSetButtonMutation.graphql.js

https://github.com/NCI-GDC/gdcapi/pull/835

♻️ remove -> remove_from

---

src/packages/@ncigdc/modern_components/environment.js

having trouble with memoizee, putting this here for testing

✨ simple hash caching for modern env

---

src/packages/@ncigdc/components/Header.js
src/packages/@ncigdc/components/Links/ManageSetsLink.js
src/packages/@ncigdc/components/Modals/SaveSetModal.js
src/packages/@ncigdc/components/PortalContainer.js
src/packages/@ncigdc/dux/sets.js
src/packages/@ncigdc/modern_components/Counts/Count.js
src/packages/@ncigdc/routes/ManageSetsRoute/ManageSetsPage.js
src/packages/@ncigdc/routes/ManageSetsRoute/index.js
src/packages/@ncigdc/theme/icons/Pencil.js
src/packages/@ncigdc/uikit/ButtonWithSpinner.js
src/packages/@ncigdc/uikit/EditableLabel.js
src/packages/@ncigdc/uikit/WarningBox.js

~~doesn't use the streaming `DownloadButton` component for the dl tsv/json yet trying to figure out why errors here https://github.com/NCI-GDC/gdcapi/blob/0b29587d19c836b0276d98c29b7d2c1eded31ef4/gdcapi/resources/index/v0.py#L33~~ figured it out, needed to update elasticsearchpy locally

:sparkles: PRTL-1597 add Manage Sets page

---

src/packages/@ncigdc/components/Modals/SaveSetModal.js
src/packages/@ncigdc/utils/__tests__/filtersToName.test.js
src/packages/@ncigdc/utils/filtersToName.js

✨ [PRTL-1605] suggest set names proper handling of sets

---

src/packages/@ncigdc/components/Links/ManageSetsLink.js
src/packages/@ncigdc/components/Modals/AppendSetModal.js
src/packages/@ncigdc/components/Modals/RemoveSetModal.js
src/packages/@ncigdc/components/Modals/SaveSetModal.js
src/packages/@ncigdc/components/Modals/onSaveComplete.js
src/packages/@ncigdc/dux/notification.js
src/packages/@ncigdc/uikit/Notification.js

The bug where the first notification doesn't display is unrelated to this and fixed in https://github.com/NCI-GDC/portal-ui/pull/2061

✨ [PRTL-1610] popup with link to manage sets on success save

---

src/packages/@ncigdc/components/Modals/BaseModal.js
src/packages/@ncigdc/components/Modals/SaveSetModal.js
src/packages/@ncigdc/modern_components/setButtons/SetButtonBase.js

the large diff in SetButtonBase is just moving the click handler to withHandlers

:sparkles: PRTL-1609 save set on enter key down

---

src/packages/@ncigdc/components/Modals/BaseModal.js
src/packages/@ncigdc/components/Modals/UserProfileModal.js
src/packages/@ncigdc/components/UserDropdown.js
src/packages/@ncigdc/theme/icons/Check.js
src/packages/@ncigdc/theme/icons/SignOut.js
src/packages/@ncigdc/theme/icons/User.js

1458 user profile page

---

src/packages/@ncigdc/components/SetTable.js
src/packages/@ncigdc/components/analysis/SetOperations/SetTable.js
src/packages/@ncigdc/modern_components/Counts/Count.js

count was initialized to 0, empty string should be good enough for this, but might want to handle this differently later on

💄 [PRTL-1643, PRTL-1653] Count init to empty string

---

src/packages/@ncigdc/modern_components/ProjectSummary/ProjectSummary.js
src/packages/@ncigdc/tableModels/projectsTableModel.js
src/packages/@ncigdc/uikit/CollapsibleList.js

1687, 1688 tweak multiple disease type/primary site 

---

data/schema.graphql
data/schema.json
package-lock.json
src/packages/@ncigdc/components/Aggregations/RangeFacet.js
src/packages/@ncigdc/components/EntityPageVerticalTable.js
src/packages/@ncigdc/components/FacetWrapper.js
src/packages/@ncigdc/components/analysis/availableAnalysis.js
src/packages/@ncigdc/containers/CaseAggregations.js
src/packages/@ncigdc/containers/explore/CaseAggregations.js
src/packages/@ncigdc/modern_components/CohortComparison/CohortComparison.js
src/packages/@ncigdc/modern_components/CohortComparison/CohortComparison.relay.js
src/packages/@ncigdc/modern_components/CohortComparison/FacetTable.js
src/packages/@ncigdc/utils/ageDisplay.js

requires https://github.com/NCI-GDC/gdcapi/pull/849

1668 analysis - age at diagnosis graph

---

src/packages/@ncigdc/modern_components/CohortComparison/Survival.js

goes with https://github.com/NCI-GDC/gdcapi/pull/853

🐛 [PRTL-1758] update survival filter

---

src/packages/@ncigdc/components/ExploringLinks.js
src/packages/@ncigdc/components/UploadSetButton.js
src/packages/@ncigdc/components/analysis/SetOperations/OpsTable.js
src/packages/@ncigdc/components/survivalPlot.css
src/packages/@ncigdc/modern_components/CohortComparison/CohortComparison.js
src/packages/@ncigdc/modern_components/CohortComparison/Survival.js
src/packages/@ncigdc/modern_components/HumanBody/humanbody.css
src/packages/@ncigdc/routes/ManageSetsRoute/ManageSetsPage.js
src/packages/@ncigdc/tableModels/utils.js

contrast and checkbox needing aria-label issues

♿️ fix 508s

---

src/Portal.js

this makes it really easy to modify the store from the console (by dispatching an action) which is very handy for testing such as adding known sets vs resaving them all the time.

✨ expose redux store for quicker testing

---

src/packages/@ncigdc/components/analysis/AnalysisResult.js
src/packages/@ncigdc/components/analysis/DemoButton.js
src/packages/@ncigdc/components/analysis/availableAnalysis.js
src/packages/@ncigdc/dux/analysis.js
src/packages/@ncigdc/routes/AnalysisRoute.js

1763 demo tab

---

src/packages/@ncigdc/components/CartDownloadDropdown.js
src/packages/@ncigdc/utils/auth/index.js

fix CartDownloadDropdown.js:L92, should pass authorized files not open files

:bug: PRTL-1859 download access modal: pass in auth not open files

---

src/packages/@ncigdc/components/Charts/Venn/buildOps.js
src/packages/@ncigdc/components/analysis/SetOperations/OpsTable.js

this fixes unicode parsing error when python's trying to create a file

🐛 [PRTL-1860] weird unicode minus sign errored on server

---

src/packages/@ncigdc/components/analysis/Demo.js
src/packages/@ncigdc/components/analysis/DemoButton.js
src/packages/@ncigdc/components/analysis/availableAnalysis.js

so I'm pretty sure this code fixes the issue, but it looks like the set ids which are used in the demo have been pre made with the wrong filters.

✏️ [PRTL-1838] update demo queries

---

src/packages/@ncigdc/modern_components/PortalSummary/PortalSummary.js

@jbarno is this what you wanted, need any more?

PRTL-1871 test- selectors on PortalSummary

---

src/packages/@ncigdc/components/SampleSheetDownloadButton.js
src/packages/@ncigdc/containers/CartPage.js

https://github.com/NCI-GDC/gdcapi/pull/867

:sparkles: PRTL-1872 sample sheet

---

src/packages/@ncigdc/containers/explore/ExplorePage.js

My bad, didn't notice `push` was needed in this page and removed withRouter HOC from the compose; broke the 'View in Repo' link. Adding it back, and destructuring props so it's easier to see needed props.

:bug: Explore: fix view in rep link

---

data/schema.graphql
data/schema.json
src/packages/@ncigdc/components/Aggregations/TermAggregation.js
src/packages/@ncigdc/components/DownloadTableToTsvButton.js
src/packages/@ncigdc/components/Impacts/ImpactTdContents.js
src/packages/@ncigdc/components/Impacts/ImpactThContents.js
src/packages/@ncigdc/components/Impacts/index.js
src/packages/@ncigdc/components/Oncogrid/getQueries.js
src/packages/@ncigdc/containers/explore/SSMAggregations.js
src/packages/@ncigdc/modern_components/ConsequencesTable/ConsequencesTable.js
src/packages/@ncigdc/modern_components/ConsequencesTable/ConsequencesTable.relay.js
src/packages/@ncigdc/modern_components/SsmSummary/SsmSummary.js
src/packages/@ncigdc/modern_components/SsmSummary/SsmSummary.relay.js
src/packages/@ncigdc/modern_components/SsmsTable/SsmsTable.model.js
src/packages/@ncigdc/modern_components/SsmsTable/SsmsTable.relay.js
src/packages/@ncigdc/modern_components/SsmsTable/mapData.js
src/packages/@ncigdc/theme/icons/BubbleIcon.js
src/packages/@ncigdc/theme/versions/active.js
src/packages/@ncigdc/utils/constants.js

~~wip~~ done, requires using `doorman` api

1404 sift polyphen update

---

src/packages/@ncigdc/components/Oncogrid/getQueries.js
src/packages/@ncigdc/modern_components/ConsequencesTable/ConsequencesTable.js
src/packages/@ncigdc/modern_components/Lolliplot/Lolliplot.js
src/packages/@ncigdc/modern_components/SsmSummary/SsmSummary.js
src/packages/@ncigdc/modern_components/SsmSummary/SsmSummary.relay.js
src/packages/@ncigdc/modern_components/SsmsTable/SsmsTable.model.js
src/packages/@ncigdc/modern_components/SsmsTable/SsmsTable.relay.js
src/packages/@ncigdc/modern_components/SsmsTable/mapData.js
src/packages/@ncigdc/theme/versions/active.js

Doorman release was decided to have annotations on one transcript only, which might not be canonical transcript; reverting back to displaying this 'functional' transcript.

PRTL-1924 revert is_canoical filter

---

src/packages/@ncigdc/components/Oncogrid/getQueries.js
src/packages/@ncigdc/modern_components/ConsequencesTable/ConsequencesTable.js
src/packages/@ncigdc/modern_components/Lolliplot/Lolliplot.js
src/packages/@ncigdc/modern_components/SsmSummary/SsmSummary.js
src/packages/@ncigdc/modern_components/SsmSummary/SsmSummary.relay.js
src/packages/@ncigdc/modern_components/SsmsTable/SsmsTable.model.js
src/packages/@ncigdc/modern_components/SsmsTable/SsmsTable.relay.js
src/packages/@ncigdc/modern_components/SsmsTable/mapData.js
src/packages/@ncigdc/theme/versions/active.js

This reverts commit 7dbb35f0990f1f2ee7e9bcfec168ae742aa521a6.

Revert "PRTL-1924 revert is_canoical filter (#2242)"

---

src/packages/@ncigdc/uikit/Tabs.js

Also fixes horizontal shifting of list in Chrome.

PRTL-1947 - Hides scrollbars and right border in IE.

---

src/packages/@ncigdc/components/ZoomableImage.js
src/packages/@ncigdc/modern_components/ImageViewer/ImageViewerTab.js
src/packages/@ncigdc/modern_components/ImageViewer/styles.css

2050 image viewer sub

---

src/packages/@ncigdc/dux/tableColumns.js
src/packages/@ncigdc/modern_components/ExploreCasesTable/ExploreCasesTable.model.js

- reset if versions dont match

:sparkles: 2068 version tableColumns

---

src/packages/@ncigdc/components/File.js
src/packages/@ncigdc/utils/constants.js

We neglected keeping the image viewer env flag functionality, make it work again

:checkered_flag: make image viewer flag work again

---

package-lock.json
package.json

https://jira.opensciencedatacloud.org/browse/PRTL-2084

⚠️ PRTL-2084 update moment

---

src/packages/@ncigdc/components/AddToCartButtonAll.js
src/packages/@ncigdc/components/AddToCartButtonSingle.js
src/packages/@ncigdc/modern_components/BiospecimenCard/BioTreeView.js
src/packages/@ncigdc/theme/icons/ShoppingCart.js

Also adds styling to cart buttons on case summary and biotree details.

✨ PRTL-2081-search-for-bio-type

---

src/packages/@ncigdc/components/DownloadButton.js
src/packages/@ncigdc/components/TableActions.js
src/packages/@ncigdc/modern_components/DownloadBiospecimenDropdown/DownloadBiospecimenDropdown.js
src/packages/@ncigdc/modern_components/withSetAction/SetActionButton.js
src/packages/@ncigdc/modern_components/withSetAction/mutations.js
src/packages/@ncigdc/modern_components/withSetAction/withSetAction.js

Create a set for biospecimen button if filters are selected.

[PRTL-2003] Adjust Clinical and Biospecimen button data method

---

src/packages/@ncigdc/components/DownloadButton.js
src/packages/@ncigdc/components/File.js
src/packages/@ncigdc/components/FileVersionsTable.js
src/packages/@ncigdc/modern_components/DownloadClinicalDropdown/DownloadClinicalDropdown.js

w/ mocked data, waiting for real endpoint

:sparkles: PRTL-2015 file versioning table

---

src/packages/@ncigdc/components/Modals/SaveSetModal.js

Added a warning for NaN value; disabled enter when NaN value.

[PRTL-1983] Disable Enter to save set when save button is disabled

---

src/packages/@ncigdc/components/CartDownloadDropdown.js
src/packages/@ncigdc/components/FilesCount.js
src/packages/@ncigdc/modern_components/ProjectsCharts/ProjectsCharts.js

Also some formatting, extra props check in FilesCount

🐛 Updates cart access error link.

---

src/packages/@ncigdc/modern_components/GenesTable/GenesTable.model.js
src/packages/@ncigdc/modern_components/GenesTable/GenesTable.relay.js

🐛PRTL-2352 fix across gdc ssm

---

package-lock.json
src/packages/@ncigdc/modern_components/CancerDistributionTable/CancerDistributionTable.tsx

Reverts NCI-GDC/portal-ui#2411

Revert "Button removed"

---

src/packages/@ncigdc/modern_components/BiospecimenCard/BiospecimenCard.js

complementary to: https://github.com/NCI-GDC/portal-ui/pull/2422

🐛 [PRTL-2070] add file size units to biospecimen clinical files

---

src/packages/@ncigdc/modern_components/SsmsTable/SsmsTable.model.js

Deleted ternary statement @ line 185, to remove the exception for genes pages.

🐛 [PRTL-2381] update exploration link

---

src/packages/@ncigdc/containers/explore/ClinicalAggregations.tsx
src/packages/@ncigdc/containers/explore/presetFacets.ts
src/packages/@ncigdc/dux/facetsExpandedStatus.ts

Also 
Add `state` to the blacklisted fields PRTL-2499
Cannot Expand All is category bar is collapsed PRTL-2519

[PRTL-2520] Reduce padding between facets to show more

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalAnalysisResult.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ControlPanelNode.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/reactToggle.css
src/packages/@ncigdc/uikit/Highlight.js

updates to `Highlight.js` came from `PRTL-2447` branch

Prtl 2452 search

---

package-lock.json
package.json
src/packages/@ncigdc/containers/explore/ClinicalAggregations.tsx

WIP. this component can and should be abstracted into a reusable component.

PRTL-2500 add “no data” component to empty categories

---

src/packages/@ncigdc/components/Charts/BarChart.js
src/packages/@ncigdc/components/Charts/FilteredStackedBarChart.js
src/packages/@ncigdc/components/Charts/StackedBarChart.js
src/packages/@ncigdc/components/Charts/TwoBarChart.js
src/packages/@ncigdc/components/SurvivalPlotWrapper.js
src/packages/@ncigdc/modern_components/CohortComparison/CohortComparison.js
src/packages/@ncigdc/modern_components/CohortComparison/FacetTable.js
src/packages/@ncigdc/modern_components/GenesBarChart/GenesBarChart.js
src/packages/@ncigdc/utils/wrapSvg.js

for review: look at the 'rotate & truncate' commit, and this
https://github.com/NCI-GDC/portal-ui/pull/2528/commits/4015fc708c3123c7cdcb99529b4479557e3652d3#diff-02b7382bb8999d242d665f1fd7442f99L95

[PRTL-1896] rotate & truncate histogram X-axis labels

---

.travis.yml
awgbuild.sh
awgdocker.sh

Signed-off-by: Bilal Baqar <mbilalbaqar@gmail.com>

Changes for awgportal

---

.eslintrc.js
config-overrides.js
package-lock.json
package.json
src/packages/@ncigdc/components/EntityPageHorizontalTable.js
src/packages/@ncigdc/containers/explore/ClinicalAggregations.tsx
src/packages/@ncigdc/containers/explore/ExplorePage.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalAnalysisResult.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/helpers.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ControlPanelNode.js
src/packages/@ncigdc/utils/ageDisplay.js
src/packages/@ncigdc/utils/constants.js
src/packages/@ncigdc/utils/customisation.js

Not the classiest solution, but gets it done for now.

PRTL 2540 capitalise terms

---

.eslintrc.js
package-lock.json
package.json
src/packages/@ncigdc/components/Modals/RemoveSetModal.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalAnalysisResult.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalAnalysisResult.relay.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js
src/packages/@ncigdc/modern_components/withSetAction/SetActionButton.js
src/packages/@ncigdc/modern_components/withSetAction/index.js
src/packages/@ncigdc/utils/filters/index.ts

Currently, when combining “_missing” and any other values creates a logical error in the query.

[PRTL-2581] fix case removal of “_missing” and other values

---

src/packages/@ncigdc/containers/explore/ClinicalAggregations.tsx

PRTL-2588, as seen both in the PR title, and single commit message.
`dev-oicr`.
Rather than using css flexbox sorting, it actually reorganises the array itself.
Also reduces “no data available” messages’ font size, as per @rosibaj’s earlier request.

[PRTL-2588] improve custom sorting to show more and less

---

src/packages/@ncigdc/components/Modals/AppendSetModal.js
src/packages/@ncigdc/components/Modals/RemoveSetModal.js

n/a
- [x ] `dev-oicr`
remove console.log statements

remove console.logs

---

src/packages/@ncigdc/modern_components/ClinicalCard/ClinicalCard.js
src/packages/@ncigdc/modern_components/ClinicalCard/ClinicalCard.relay.js

PRTL-2582, PRTL-2584
?
Adds the requested fields to the entities viewer.

Add Synchronous Malignancy and Packs Years Smoked to Case entities

---

.gitignore
src/packages/@ncigdc/components/analysis/AnalysisResult.js
src/packages/@ncigdc/uikit/Tooltip/index.js
src/packages/@ncigdc/uikit/Tooltip/withTooltip.js
src/packages/@ncigdc/uikit/UnstyledButton.js
tslint.json

PRTL-2594
Adds Tooltip component to the tab label, in order to display the full tag, rather than its truncated version.

[PRTL-2594] add tooltip to truncated tab label

---

src/packages/@ncigdc/components/GitHut/index.js
src/packages/@ncigdc/components/Modals/NoAccessModal.js
src/packages/@ncigdc/components/analysis/Demo.js
src/packages/@ncigdc/modern_components/withSetAction/SetActionButton.js
src/packages/@ncigdc/routes/utils.js
src/packages/@ncigdc/uikit/Sortable/sortable.js
src/packages/@ncigdc/uikit/withDropdown.js
src/packages/@ncigdc/utils/withPropsOnChange.js

n/a
Reverting UNSAFE prefix on lifecycle methods

revert UNSAFE method changes

---

src/packages/@ncigdc/components/analysis/ClinicalAnalysisLaunch.tsx

PRTL-2576
Just removed hardcoded `disable` on cdave launch demo button

💄 PRTL-2576 enable cdave launch demo button

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js
src/packages/@ncigdc/modern_components/DownloadBiospecimenDropdown/DownloadBiospecimenDropdown.js
src/packages/@ncigdc/modern_components/DownloadClinicalDropdown/DownloadClinicalDropdown.js
src/packages/@ncigdc/theme/mixins.js
src/packages/@ncigdc/uikit/Dropdown.js

PRTL-2585
Clinical Analysis - disable set actions when no buckets selected, add disabled styling, reorder so tsv button is last on list. Align bins dropdown to right
General - Default border radius for all dropdowns

💄Feature/PRTL-2585 style set action menu

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js

removessss extra s'ssssss

---

src/packages/@ncigdc/components/Modals/GroupValuesModal.tsx
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js

PRTL-2602
Changed reset function in GroupValuesModal.

[PRTL-2602] Changed reset function in GroupValuesModal.

---

.eslintrc.js
src/packages/@ncigdc/components/Modals/GroupValuesModal.tsx
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js

PRTL-2610
Change the withPropsOnChange listener to 
`!isEqual(props.dataBuckets, nextProps.dataBuckets) || props.setId === nextProps.setId`

[PRTL-2610] Fix On Switch Cohort

---

src/packages/@ncigdc/components/analysis/AnalysisResult.js
src/packages/@ncigdc/components/analysis/CreateAnalysis.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js
src/packages/@ncigdc/modern_components/QQPlot/QQPlotQuery.js

PRTL-2603
New clinical analysis will have default name `Custom Analysis <savedAnalyses.length + 1>`
changes props watched for qq plot to prevent redundant requests

🚸PRTL-2603 default analysis name

---

package-lock.json
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ContinuousAggregationQuery.js

e.g. PRTL-2566
Added Range to Continuous Binning Query

[PRTL-2566] Added Range to Continuous Binning Query

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalAnalysisResult.js

PRTL-2617
Fixes cohort dropdown styling

💄PRTL-2617 revert styles from bad merge

---

src/packages/@ncigdc/components/analysis/availableAnalysis.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalAnalysisResult.js

PRTL-2633
text updates on cdave launch and control panel

💄 PRTL-2633 Text updates on analysis launch and control panel.

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js

PRTL-2632
turn off reset option if bins have not been modified

[PRTL-2632] disable reset bin dropdown item

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js

PRTL-2639
Show continuous buckets in ascending order.

[PRTL-2639] ascending order buckets

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js
src/packages/@ncigdc/utils/constants.js

PRTL-2448
Added analysis colors for each category of buckets.

[PRTL-2448] Change Colour Scheme for Analysis

---

package-lock.json
package.json

Updates the package version to one where the bug has been resolved.

[PRTL-2613] fix boxplot not rerendering when data changes

---

src/packages/@ncigdc/components/Aggregations/FacetHeader.js

PRTL-2647
Sets facet header collapse action on inner header row only, not reset button

🐛 PRTL-2647 set header collapse action on inner header row

---

src/packages/@ncigdc/components/Modals/ContinuousBinning/ContinuousCustomBinsModal.js

related to PRTL-2462
Get correct values from user's custom bins

[bug] fix custom interval bin editing

---

src/packages/@ncigdc/components/Modals/ContinuousBinning/ContinuousCustomBinsModal.js
src/packages/@ncigdc/components/Modals/ContinuousBinning/RangeInputRow.js
src/packages/@ncigdc/components/Modals/ContinuousBinning/RangeTableRow.js
src/packages/@ncigdc/components/PortalContainer.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js

PRTL-2622
Adds a permanent new row to the manual range table for continuous binning.
Removes functionality for adding new rows when the last row is saved or deleted.

[PRTL-2622] empty row

---

src/packages/@ncigdc/components/Modals/ContinuousBinning/ContinuousCustomBinsModal.js
src/packages/@ncigdc/components/analysis/defaultCDAVEvariables.js
src/packages/@ncigdc/dux/analysis.ts
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js

PRTL 2656
Save the user's custom continuous interval to redux instead of reverse engineering it based on the buckets.

[PRTL 2656] custom interval

---

src/packages/@ncigdc/components/Aggregations/FacetHeader.js
src/packages/@ncigdc/utils/constants.js

[PRTL-2648] add BMI header to capitaliser

---

build.sh
src/packages/@ncigdc/utils/constants.js

GDCDEVOPS-254
Update container build for the UAT environment.

feat(GDCDEVOPS-254): set up qa uat environment

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ContinuousAggregationQuery.js
src/packages/@ncigdc/utils/string.ts

PRTL-2661
use UAT api url
Adds extra null check on defaultContinuousData.
Adds helper function for creating facet key names

🐛 PRTL-2661 Correct invalid null results on variable cards

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js

e.g. PRTL-2660
Added the percentage after the tooltip in histogram.

[PRTL-2660] Tooltip not showing percent on histogram

---

.gitignore
package-lock.json
package.json
src/packages/@ncigdc/components/SurvivalPlotWrapper.js
src/packages/@ncigdc/utils/survivalplot.js

PRTL-2649
with UAT api url
Allows dataSets with less than minimum allowed cases to keep curve numbers and colours in sync
Updates survival plot to version 0.8.3

🐛PRTL-2649 mislabeled survival plot lines

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js

PRTL-2655
Continuous bins need `groupName` and `doc_count`, and when you refresh the bins without changing the query, you don't get both pieces of info from one source. So I combined 2 sources to create the expected format for the bins.

[PRTL-2655] Manual continuous bins not refreshing

---

src/packages/@ncigdc/components/SurvivalPlotWrapper.js

e.g. PRTL-2654
Assign a default value to legend in survivalplotwrapper to prevent undefined error.

[PRTL-2654] User is unable to download image files from Production Portal

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js

PRTL-2674
ascending order in table under survival chart

[PRTL-2674] ascending order under survival plot

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ControlPanelNode.js

e.g. PRTL-2668
Group AJCC in Same Order as Clinical Tab

[PRTL-2668] Group AJCC in Same Order as Clinical Tab

---

package-lock.json
src/packages/@ncigdc/components/Modals/GroupValuesModal.tsx

[SUBP-533] fix Categorical binning modal overflow

---

src/packages/@ncigdc/components/Modals/ContinuousBinning/ContinuousCustomBinsModal.js
src/packages/@ncigdc/components/Modals/ContinuousBinning/RangeInputRow.js
src/packages/@ncigdc/components/PortalContainer.js

PRTL-2681
only validate the last row if it has input

[PRTL-2681] only validate the last row if it has input

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js

e.g. PRTL-2669
capitalize card titles

[PRTL-2669]capitalize card titles

---

src/packages/@ncigdc/components/Modals/ContinuousBinning/ContinuousCustomBinsModal.js
src/packages/@ncigdc/components/Modals/ContinuousBinning/CustomIntervalInput.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ContinuousAggregationQuery.js
src/packages/@ncigdc/utils/string.ts

PRTL-2663
- update continuous bins, including custom binning, to work with negative numbers
- rename 'quartile' to 'quarter'
- change 'less than' to `<`
- add utilities for parsing continuous bucket names

[PRTL-2663] negative range in continuous bins

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalAnalysisResult.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ControlPanelNode.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/reactToggle.css

[PRTL-2670] add colours to Analysis result toggles

---

.vscode/settings.json

N/A
Stop VSCode from using its default formatter on this project.

[chore] disable vscode formatting

---

package-lock.json
package.json
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js

As described in the title.
Bonus: addresses a Lodash security vulnerability.

[PRTL-2687] adjust decimal handling at continuous data table

---

src/packages/@ncigdc/modern_components/HumanBody/humanbody.css

PRTL-2685
Make CSS more specific for the homepage illustration. It was applying styling unintentionally (e.g. Clinical Analysis table checkboxes)

[PRTL-2685] fix floating checkbox

---

.eslintrc.js
src/packages/@ncigdc/modern_components/QQPlot/QQPlotQuery.js

[PRTL-2690] add case ID column to QQ TSV

---

src/packages/@ncigdc/components/Modals/ContinuousBinning/ContinuousCustomBinsModal.js
src/packages/@ncigdc/components/SurvivalPlotWrapper.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js

PRTL-2683
- make box/qq plot titles darker
- fix button text & unique IDs
- increase contrast of survival plot labels

[PRTL-2683] accessibility

---

package-lock.json
package.json
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js
src/packages/@ncigdc/modern_components/QQPlot/QQPlot.js
src/packages/@ncigdc/modern_components/QQPlot/QQPlotQuery.js

PRTL-2652
Updates boxplot to version with custom colour
Sets numerical plot colours to current clinical type

🐛Bugfix/PRTL-2652 update numerical plot colours

---

src/packages/@ncigdc/components/DownloadTableToTsvButton.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js

PRTL-2688
Remove the "Select" column from TSV downloads in Clinical Analysis cards.

[PRTL-2688] remove select from histogram TSV

---

src/packages/@ncigdc/containers/explore/CaseAggregations.js
src/packages/@ncigdc/modern_components/CaseAggregations/CaseAggregations.js
src/packages/@ncigdc/modern_components/FacetSelection/FacetSelection.js
src/packages/@ncigdc/modern_components/FileAggregations/FileAggregations.js

PRTL-2571
Allows custom case sensitivity on custom facet search, sets case insensitive in repository only.
Some refactoring of affected components.

✨🎨 PRTL-2571 Option for custom facet search to be case insensitive. Refactoring

---

.eslintrc.js
src/packages/@ncigdc/components/EntityPageHorizontalTable.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js

[PRTL-2693] fix undefined categorical bin tooltip labels

---

src/packages/@ncigdc/components/EntityPageHorizontalTable.js

PRTL-2706
Revert string coercion on entity table header

🐛 PRTL-2706 Fix incorrect string coercion

---

src/packages/@ncigdc/modern_components/QQPlot/QQPlot.js

PRTL-2574
QQ plot will render with "not enough data" if there are less than 10 cases with data
Optional minimumCases prop, defaults to 10

🐛PRTL-2574 min case count for qq plot

---

src/packages/@ncigdc/components/Modals/GroupValuesModal.tsx
src/packages/@ncigdc/theme/icons/Group.js
src/packages/@ncigdc/theme/icons/Ungroup.js

PRTL-2696
Styling for disabled categorical modal buttons

💄PRTL-2696 cat modal disabled button styles

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js

[PRTL-2694]Add Custom Bins indicator to the table.

---

src/packages/@ncigdc/components/Modals/ContinuousBinning/ContinuousCustomBinsModal.js
src/packages/@ncigdc/components/Modals/ContinuousBinning/RangeInputRow.js
src/packages/@ncigdc/components/Modals/ContinuousBinning/RangeTableRow.js
src/packages/@ncigdc/components/Modals/ContinuousBinning/styles.js

PRTL-2695
- rename options to actions
- update disabled button styling
- remove unnecessary actions (save/edit/cancel)

[PRTL-2695] remove unnecessary actions

---

package-lock.json
src/packages/@ncigdc/components/DownloadVisualizationButton.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/index.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/boxplot.css
src/packages/@ncigdc/modern_components/QQPlot/QQPlotQuery.js

[PRTL-2611] Merge qq/box download button.

---

package-lock.json
package.json
src/packages/@ncigdc/modern_components/QQPlot/QQPlot.js

PRTL-2605
Bug is fixed with update to boxplot 0.3.0
Portal changes include fix for incorrect merge on PRTL-2606

🐛PRTL-2605 fix boxplot yaxis units

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/CohortDropdown.js

PRTL-2564
styling/truncation for cohort select dropdown

💄 PRTL-2564 Styling changes for cohort dropdown button

---

package-lock.json
package.json

updates the package dependency to a version that rounds the tooltip values

[PRTL-2720] round 2 decimals at boxplot tooltip

---

src/packages/@ncigdc/components/Modals/BAMModal.js

PRTL-2620
add a message about unmapped values

[PRTL-2620] update text in bam slicing modal

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalAnalysisResult.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/CategoricalVariableCard.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/helpers.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/modals/CategoricalCustomBinsModal/CategoricalCustomBinsModal.tsx

PRTL-2719
- Do display _missing when there is at least 1 value in the aggregation that is not _missing
- Change the display to "Missing"
- If all cases are _missing, then show the No Data for this card status

[PRTL-2719] update _missing values for production

---

src/packages/@ncigdc/components/GDCApps/GDCAppsDropdown.js

[PRTL-2722] change DTT link

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/CategoricalVariableCard.js

PRTL-2472
Calculate the doc_count of _missing from difference of totalDocs and sum of buckets with values expect _missing.

[PRTL-2472] Wrong Total Case Count on Some Variables for "_missing"

---

src/packages/@ncigdc/components/GDCApps/GDCAppsDropdown.js

Duplicate of https://github.com/NCI-GDC/portal-ui/pull/2686 to include this fix in Redfish.

change DTT link

---

data/getSchema.js
data/schema.graphql
data/schema.json
src/packages/@ncigdc/components/EntityPageVerticalTable.js
src/packages/@ncigdc/modern_components/GeneExternalReferences/GeneExternalReferences.js
src/packages/@ncigdc/modern_components/GeneExternalReferences/GeneExternalReferences.relay.js
src/packages/@ncigdc/modern_components/GeneExternalReferences/index.js
src/packages/@ncigdc/modern_components/GeneSummary/GeneSummary.js
src/packages/@ncigdc/modern_components/GeneSummary/GeneSummary.relay.js
src/packages/@ncigdc/modern_components/GeneSummary/index.js
src/packages/@ncigdc/modern_components/SsmExternalReferences/SsmExternalReferences.js
src/packages/@ncigdc/modern_components/SsmExternalReferences/SsmExternalReferences.relay.js
src/packages/@ncigdc/modern_components/SsmExternalReferences/index.js
src/packages/@ncigdc/modern_components/SsmSummary/SsmSummary.js
src/packages/@ncigdc/modern_components/SsmSummary/SsmSummary.relay.js
src/packages/@ncigdc/modern_components/SsmSummary/index.js
src/packages/@ncigdc/routes/GeneRoute/GeneRoute.tsx
src/packages/@ncigdc/routes/GeneRoute/index.tsx
src/packages/@ncigdc/routes/SSMRoute/SSMRoute.js
src/packages/@ncigdc/routes/SSMRoute/index.js
src/packages/@ncigdc/theme/global.css
src/packages/@ncigdc/utils/externalReferenceLinks.js

Readds the reverted CIViC attributes

[PRTL-2534] re-add CIViC attributes

---

Dockerfile
src/packages/@ncigdc/components/GDCApps/GDCAppsDropdown.js

GDCDEVOPS-305
Minor version of nginx has been bumped due to security vulnerability

Bumped up the version of nginx

---

src/packages/@ncigdc/containers/explore/ExplorePage.js

PRTL-2741
add minimum height for resizing the facet panel

[PRTL-2741] facet panel height

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/ContinuousVariableCard.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ContinuousAggregationQuery.js

PRTL-2754
Adds default props for bins, defines getContinuousBins independent of data to prevent crash on cards without data

PRTL-2754 Bugfix/no data on continuous crash

---

src/packages/@ncigdc/components/analysis/CreateAnalysis.js
src/packages/@ncigdc/components/analysis/SelectSet.js
src/packages/@ncigdc/components/analysis/availableAnalysis.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/CohortDropdown.js

PRTL-2742
1. Abandon ClinicalAnalysisLaunch.tsx file and move all its union logic into SelectedSet.js file since they have 80% common code. 
2. Correct duplicate variables errors in SelectedSet.js file.
3. Apply layout style of ClinicalAnalysisLaunch to selectedSet.
4. Add textOverflow: 'ellipsis' and tooltips to CohortDropdown.
5. Fix a checkbox error which is for selecting sets component, when uncheck a checkbox, all the selected checkbox will be unselected.

[PRTL-2742] Analysis Layout Enhancements & Fixes

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/ClinicalVariableCard.js

PRTL-2761
update the dispatch action for the percentage/number radio buttons

[PRTL-2761] fix radio buttons

---

src/packages/@ncigdc/components/GDCApps/GDCAppsDropdown.js
src/packages/@ncigdc/components/PortalContainer.js

[PRTL-2744] wrong back button

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/ClinicalVariableCard.js

PRTL-2769
change no data message

[PRTL-2769] update no data message

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/modals/CategoricalCustomBinsModal/CategoricalCustomBinsModal.tsx

Replaces `_missing` with `Missing`

[PRTL-2775] replace missing label

---

.eslintrc.js
src/packages/@ncigdc/containers/explore/ExplorePage.js
src/packages/@ncigdc/modern_components/ClinicalAggregations/ClinicalAggregations.js
src/packages/@ncigdc/modern_components/ClinicalAggregations/ClinicalAggregations.relay.js
src/packages/@ncigdc/modern_components/ClinicalAggregations/ClinicalAggregations.tsx
src/packages/@ncigdc/modern_components/ClinicalAggregations/index.js
src/packages/@ncigdc/modern_components/IntrospectiveType/ClinicalAnalysisContainer.js
src/packages/@ncigdc/modern_components/IntrospectiveType/Introspective.relay.js
src/packages/@ncigdc/utils/clinicalBlacklist.ts
src/packages/@ncigdc/utils/constants.js
src/packages/@ncigdc/utils/withFacetSelection.js

PRTL-2740
Converts ClinicalAggregations to modern relay, will then show loaders.

🚸 PRTL-2740 clinical aggs loader

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ContinuousAggregationQuery.js

shows a "loading" animation whenever changes are applied

[PRTL 2774] improve continuous query loading logic

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalAnalysisResult.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/ClinicalVariableCard.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/components/ClinicalBoxPlot.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/print.css

PRTL-2841
very important to note: printing in firefox is weird and broken. it especially dislikes flexbox.
- make everything `display: block` in print CSS (unless it has a more specific rule for a different display property)
- add some floats, padding, and width properties where necessary

[PRTL-2841] firefox printing issues

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ContinuousAggregationQuery.js

PRTL-2848
replace the `Loader` component with a `Spinner` so it doesn't block the page

[PRTL-2848] change loader to spinner

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/ClinicalVariableCard.js

removes the button as instructed

[PRTL-2845] avoid box qq for years of

---

src/packages/@ncigdc/components/SurvivalPlotWrapper.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/CategoricalVariableCard.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/ClinicalVariableCard.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/ContinuousVariableCard.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/EnhancedClinicalVariableCard.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/components/ClinicalSurvivalPlot.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/helpers.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/CohortDropdown.js
src/packages/@ncigdc/utils/survivalplot.js

🐛 PRTL-2750 preserve survival colours

---

src/packages/@ncigdc/containers/explore/ExplorePage.js
src/packages/@ncigdc/utils/constants.js

n/a
Add feature flag for summary page

✨ Add summary page feature flag

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/CategoricalVariableCard.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalVariableCard/modals/CategoricalCustomBinsModal/CategoricalCustomBinsModal.tsx

Changes all 'Missing' to 'missing' in categorical bins.

[PRTL-2855] change cassing for ‘Missing’

---

src/packages/@ncigdc/modern_components/Lolliplot/LolliplotWrapper.js

Adds an extra string casing control, to ensure accuracy of the condition to fill the dropdown.

[PRTL-2850] restore protein viewer transcript dropdown

---

src/packages/@ncigdc/components/Charts/Venn/VennSvg.js
src/packages/@ncigdc/components/analysis/AnalysisResult.js
src/packages/@ncigdc/components/analysis/SetOperations/SetOperations.js
src/packages/@ncigdc/components/analysis/availableAnalysis.js

adds container specificity to avoid ID duplication

[PRTL-2861] add context specificity to duplicate IDs

---

src/packages/@ncigdc/components/Aggregations/TermAggregation.js

PRTL-2877
make filters on the project entity pages case-agnostic

[PRTL-2877] data category normalization

---

src/packages/@ncigdc/components/Explore/SummaryPage/CardWrapper.js
src/packages/@ncigdc/components/Explore/SummaryPage/SurvivalAnalysisCard.js
src/packages/@ncigdc/components/Explore/SummaryPage/index.js
src/packages/@ncigdc/components/SurvivalPlotWrapper.js
src/packages/@ncigdc/components/VisualizationHeader.js

e.g. PRTL-2698
Add SurvivalAnalysisCard in Summary Page.

[PRTL-2698] Add Overall Survival Card to Summary Tab

---

public/index.html

PRTL-2868
Added a text message for IE users who would otherwise see a blank screen.

[PRTL-2868] Internet Explorer message

---

src/packages/@ncigdc/modern_components/ProjectSummary/ProjectSummary.tsx

PRTL-2436
negate the `text-transform` capitalization for `<Th />` elements

[PRTL-2436] dbGaP capitalization

---

src/packages/@ncigdc/components/DownloadTableToTsvButton.js
src/packages/@ncigdc/modern_components/ProjectsTable/ProjectsTable.js
src/packages/@ncigdc/modern_components/ProjectsTable/ProjectsTable.model.js

PRTL-2883
Adds collapsed fields to data-attribute to pass to tsv download.

🐛 PRTL-2883 Pass collapsed values in data attribute

---

src/packages/@ncigdc/components/Aggregations/SuggestionFacet.js
src/packages/@ncigdc/modern_components/SuggestionFacet/SuggestionFacet.js
src/packages/@ncigdc/uikit/withDropdown.js

PRTL-2587
- add `onClick` event for search bars (same as the `onChange` event)
- note: there are 2 types of search bars
- for the dropdown: don't close the search dropdown if the user clicks on the associated search input

[PRTL-2587] add onclick checks for suggestion facets & dropdown

---

src/packages/@ncigdc/containers/explore/ClinicalAggregations.tsx
src/packages/@ncigdc/dux/facetsExpandedStatus.ts
src/packages/@ncigdc/modern_components/ClinicalAggregations/ClinicalAggregations.tsx

PRTL-2906
Improves check for data changes to update clinical facets correctly.

🐛 PRTL-2906 Correct propsOnChange check for clinical aggs

---

src/packages/@ncigdc/modern_components/ClinicalAnalysis/ClinicalAnalysisResult.js
src/packages/@ncigdc/modern_components/ClinicalAnalysis/ContinuousAggregationQuery.js

PRTL-2904
- update continuous cards when you change the case set or customize bins
- move updateData out of recompose

[PRTL-2904] update continuous cards

---

src/packages/@ncigdc/containers/explore/ExplorePage.js

[PRTL-2911] Remove duplicated SummaryPage.

---

package-lock.json
package.json
src/packages/@ncigdc/modern_components/HumanBody/HumanBody.js

PRTL-2925
Also related to this https://github.com/oncojs/sapien/pull/11

Hotfix/[PRTL-2925] Fix Human Body Image Chart X-Axis overlapping

---

package-lock.json
package.json
src/packages/@ncigdc/modern_components/HumanBody/HumanBody.js

Improves visualisation of the newly added Genie data, at the homepage's human body chart X-axis.

🐳 Redfish 1.23.1 - DR21 hotfix sync 

---

src/packages/@ncigdc/components/HowToDownload.js

PRTL-2929
Adds external link on cart page to genomic reference files.

✨PRTL-2929 Add genomic ref link to cart page

---

src/packages/@ncigdc/theme/global.css

Binds the field to whatever the container's size is.

[PRTL-2771] bind textarea width to its container

---

src/packages/@ncigdc/modern_components/GeneExpression/GeneExpression.js

[PRTL-2949] open gene/case links in new tabs (inchlib 4)

---

src/packages/@ncigdc/modern_components/GeneExpression/GeneExpression.js
src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js

PRTL-2950
skip the dialog boxes for download & changing colours

[PRTL-2950] remove download & color dialogs (inchlib 5)

---

src/packages/@ncigdc/modern_components/GeneExpression/GeneExpression.js
src/packages/@ncigdc/modern_components/GeneExpression/GeneExpressionChart.js
src/packages/@ncigdc/modern_components/GeneExpression/inchlib/data/3x2.js
src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js

PRTL-2951
this PR is stacked on other inchlib PRs and has to be squash-merged in order.
- make category colours static and consistent - i.e. male is always purple
- add a legend to the screen view and PNG view

[PRTL-2951] category colours & legend (inchlib 6)

---

src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js

PRTL-2953
- add `cursor: pointer` where appropriate
- make text darker on hover
- adjust column/row highlights on the heatmap
- standardize colours and font styles
- removed a couple of things we definitely won't use i.e. row IDs

[PRTL-2953] inchlib hover adjustments

---

src/packages/@ncigdc/modern_components/GeneExpression/GeneExpressionChart.js
src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js

PRTL-2951
Some colours were incorrect in PRTL-2951, this PR fixes them.

[PRTL-2951] QA fixes

---

src/packages/@ncigdc/modern_components/AnnotationSummary/AnnotationSummary.js

PRTL-2944
Adds text wrap to annotations notes section

💄 PRTL-2944 Add overflow wrap for annotation summary notes section

---

src/packages/@ncigdc/modern_components/GeneExpression/GeneExpression.js
src/packages/@ncigdc/modern_components/GeneExpression/GeneExpressionChart.js
src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js

[PRTL-2965] legend updates

---

src/packages/@ncigdc/modern_components/HumanBody/HumanBody.js

Restores the proper attribute expected from Sapien. It also adds protective code to ensure compatibility with that package's possible changes, as well as further back-end normalisation.

[PRTL-2979] fix primary site click in human body

---

src/packages/@ncigdc/modern_components/Lolliplot/Lolliplot.js

[PRTL-2969] remove comma and case number from lolliplot mutations details panel

---

src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js

PRTL-2978
Add tooltips to dendrogram rows & columns.

[PRTL-2978] InCHlib - dendrogram tooltips

---

src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js
src/packages/@ncigdc/modern_components/GeneExpression/inchlib/style.css

PRTL-2980
Change button from having a disabled to just having a disabled class, so that it can have mouse events.

[PRTL-2980] InCHlib - show tooltips on disabled buttons

---

src/packages/@ncigdc/uikit/Notification.js

PRTL-3031
add word wrap to toast component

[PRTL-3031] Add word wrap to toast

---

src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js

PRTL-3025
- reposition row/gene tooltips
- change tooltip text: rows -> genes, columns -> cases
- remove tooltip on outermost dendrograms

[PRTL-3025] InCHlib - updates

---

src/packages/@ncigdc/components/analysis/availableAnalysis.js
src/packages/@ncigdc/theme/icons/GeneExpression.js

[PRTL-3033] add gene expression icon & description

---

src/packages/@ncigdc/components/ControlledAccessSwitch/index.js
src/packages/@ncigdc/components/ControlledAccessSwitch/styles.scss
src/packages/@ncigdc/components/SearchPage.js
src/packages/@ncigdc/containers/explore/ExplorePage.js
src/packages/@ncigdc/uikit/Button.js

Adds the Controlled Access switch (purple button), without any functionality.

[PRTL-3040] add controlled study switch component

---

src/packages/@ncigdc/modern_components/RestrictionMessage/Filter10kMessage.js

[PRTL-3048] open 10k message link in new window

---

src/packages/@ncigdc/components/ControlledAccessSwitch/index.js
src/packages/@ncigdc/utils/constants.js
src/packages/@ncigdc/utils/withControlledAccess/index.js

PRTL-3098
wrap a tooltip around the DAVE-CA switch button

[PRTL-3098] add tooltip to DAVE-CA switch button

---

src/packages/@ncigdc/components/Modals/ControlledAccess/ControlledAccessModal.js
src/packages/@ncigdc/components/Modals/ControlledAccess/helpers.js
src/packages/@ncigdc/utils/constants.js

PRTL-3105
- don't sort controlled studies if one has been selected
- only add radios to controlled studies
- add a second controlled study to the dev user

[PRTL-3105] correct radio buttons in dave-ca modal

---

src/packages/@ncigdc/components/Modals/ControlledAccess/ControlledAccessModal.js
src/packages/@ncigdc/components/Modals/ControlledAccess/helpers.js
src/packages/@ncigdc/utils/withControlledAccess/helpers.js

[PRTL-3106] DAVE-CA: show all open and in process programs

---

.travis.yml
src/packages/@ncigdc/containers/explore/ExplorePage.js
src/packages/@ncigdc/containers/explore/SSMAggregations.js
src/packages/@ncigdc/modern_components/ClinicalAggregations/ClinicalAggregations.relay.js
src/packages/@ncigdc/modern_components/ExploreCasesAggregations/ExploreCasesAggregations.relay.js
src/packages/@ncigdc/modern_components/GeneAggregations/GeneAggregations.relay.js
src/packages/@ncigdc/modern_components/GeneSymbol/GeneSymbol.relay.js
src/packages/@ncigdc/modern_components/Query.js
src/packages/@ncigdc/modern_components/SuggestionFacet/SuggestionFacet.relay.js

Adds the study param to the filters, and covers most of the side-effects of filter selection

[PRTL-3088] add Study param to Exploration filters

---

src/packages/@ncigdc/modern_components/ExploreCasesPies/ExploreCasesPies.js

Unifies the query from the shared helper. Adds the CA query param.

[PRTL-3091] add Study param to Cases pie charts

---

src/packages/@ncigdc/modern_components/DownloadBiospecimenDropdown/DownloadBiospecimenDropdown.relay.js
src/packages/@ncigdc/modern_components/DownloadClinicalDropdown/DownloadClinicalDropdown.relay.js
src/packages/@ncigdc/modern_components/ExploreCasesTable/ExploreCasesSsmsAggregations.relay.js
src/packages/@ncigdc/modern_components/ExploreCasesTable/ExploreCasesTable.relay.js

Adds the study params to the results table and the action buttons (which have an extra modifier for compatibility with the other sections we haven't added "Study" to.)

[PRTL-3092] add Study param to Cases results table

---

src/packages/@ncigdc/modern_components/GenesTable/GenesTable.relay.js
src/packages/@ncigdc/modern_components/GenesTable/SsmsAggregations.relay.js

Adds the Study param using the cacheConfig hack

[PRTL-3094] add Study param to Genes results table

---

src/packages/@ncigdc/modern_components/SsmsTable/SsmsTable.relay.js

Adds the Study param to the table.

[PRTL-3096] add Study param to Mutations results table

---

src/packages/@ncigdc/components/Explore/MutationsTab.js

Adds Study param to the Mutations survival plot

[PRTL-3089] add Study param to Mutations Survival plot

---

src/packages/@ncigdc/components/Oncogrid/OncogridWrapper.js
src/packages/@ncigdc/components/Oncogrid/getQueries.js

Adds the Study param functionality to the OncoGrid wrapper.

[PRTL-3090] add Study param to OncoGrid

---

src/packages/@ncigdc/modern_components/withSetAction/withSetAction.js

Compensates for the changes in the Relay (Modern) environment, which require passing the CA params function before generating the standard Object.

[PRTL-3118] update withSetAction to allow CA

---

src/packages/@ncigdc/components/Links/InternalLinkWithContext.js
src/packages/@ncigdc/components/Modals/AppendSetModal.js
src/packages/@ncigdc/components/Modals/RemoveSetModal.js
src/packages/@ncigdc/components/SetActions.js
src/packages/@ncigdc/modern_components/Counts/Count.js
src/packages/@ncigdc/modern_components/Counts/withCount.js
src/packages/@ncigdc/modern_components/environment.js
src/packages/@ncigdc/modern_components/withSetAction/withSetAction.js
src/packages/@ncigdc/uikit/GreyBox.tsx

Resolves a render loop caused by an unhandled query error.
See details in comments.

[PRTL-3117] fix set looping after single Study environment changes

---

src/packages/@ncigdc/modern_components/SCRNASeq/SCRNASeq.js
src/packages/@ncigdc/modern_components/SCRNASeq/SCRNASeqPlot/SCRNASeqPlot.js
src/packages/@ncigdc/modern_components/SCRNASeq/SCRNASeqPlot/utils.js
src/packages/@ncigdc/modern_components/SCRNASeq/toolbar/DownloadButton.js
src/packages/@ncigdc/modern_components/SCRNASeq/toolbar/ToolbarButton.js

PRTL-3104
- make analysis download button blue
- add dropdown items for analysis files
- rough in a click handler

[PRTL-3104] add global analysis download options

---

src/packages/@ncigdc/uikit/Banner/index.js
src/packages/@ncigdc/uikit/Banner/styles.scss

Restores the grey for the warning banner.

restore banner contrast

---

src/packages/@ncigdc/uikit/Banner/index.js
src/packages/@ncigdc/uikit/Banner/styles.scss

#2248  Environment to be used in testing
Collapses the text elements inside the collapsed banner, so there's no false positives for contrast issues.

resolve collapsed banner contrast issues

---

src/packages/@ncigdc/modern_components/ExploreCasesAggregations/ExploreCasesAggregations.relay.js

prtl-3119
hide this facet. commenting it out because it will be brought back shortly.

[prtl-3119] hide experimental strategy facet

---

src/packages/@ncigdc/components/analysis/CreateAnalysis.js
src/packages/@ncigdc/components/analysis/SelectSet.js
src/packages/@ncigdc/components/analysis/SetTable.js
src/packages/@ncigdc/components/analysis/ValidateGeneExpression.js
src/packages/@ncigdc/components/analysis/availableAnalysis.js
src/packages/@ncigdc/utils/string.ts

Enhances the set selection layout to accommodate the Gene Expression flow.

[PRTL-3129] add “select sets” for Gene Expression

---

awgbuild.sh
awgportal.Dockerfile
src/packages/@ncigdc/components/ActionsRow.js
src/packages/@ncigdc/routes/AWGRoutes.js

Preliminary implementation of the Slide Viewer functionality. Non-operative, pending API integration.

[PRTL-3156] enable Slide Image Viewer at AWG Portal

---

src/packages/@ncigdc/components/analysis/CreateAnalysis.js
src/packages/@ncigdc/components/analysis/availableAnalysis.js

PRTL-3176
just adding tooltip text

[PRTL-3176] add tooltip to scrnaseq demo button

---

src/packages/@ncigdc/components/analysis/SelectScrnaSeq/SelectScrnaSeq.js
src/packages/@ncigdc/components/analysis/SelectScrnaSeq/SelectScrnaSeq.relay.js
src/packages/@ncigdc/components/analysis/SelectScrnaSeq/SelectScrnaSeqWorkflow/SelectScrnaSeqWorkflow.relay.js

PRTL-3192
- add real scrna-seq filters for case/workflow selection

[PRTL-3192] add real scrna seq filters

---

.pre-commit-config.yaml
.secrets.baseline

This is needed in order for the repo to be managed by pre-commit.

Excluding packages-lock.json from pre-commit

---

src/packages/@ncigdc/components/analysis/SelectScrnaSeq/SelectScrnaSeq.js

PRTL-3203
reset case selection if the user clicks 'select a case' (value === '')

[PRTL-3203] handle empty case selection in scrna-seq

---

src/packages/@ncigdc/modern_components/SCRNASeq/toolbar/DownloadButton.js

PRTL-3202
remove summary from scrna download button

[PRTL-3202] remove summary from scrna download

---

src/packages/@ncigdc/modern_components/SCRNASeq/SCRNASeq.js

PRTL-3201
make scrna table links open in new window

[PRTL-3201] make scrna table links open in new window

---

src/packages/@ncigdc/modern_components/SCRNASeq/SCRNASeq.js
src/packages/@ncigdc/modern_components/SCRNASeq/SCRNASeqPlot/SCRNASeqPlot.js

PRTL-3199
fix scrna fullscreen display by moving loading spinner to the page level

[PRTL-3199] fix scrna fullscreen display

---

src/packages/@ncigdc/components/analysis/SelectScrnaSeq/SelectScrnaSeq.js
src/packages/@ncigdc/components/analysis/availableAnalysis.js

PRTL-3194
change scrna demo verbiage

[PRTL-3194] change scrna demo verbiage

---

src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js

Calculates Age at Diagnosis, in years.

[PRTL-3204] convert days to years for inchlib age at dx

---

docker-build-jenkins.sh

GDCDEVOPS-575 Pipelines leak Docker resources
Cleaning up docker images after pushing images to registry.

GDCDEVOPS-575 Pipelines Leak Docker Resources

---

src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js

PRTL-3213
change heatmap colour scheme to green-black-red

[PRTL-3213] change heatmap colour scheme

---

src/packages/@ncigdc/components/analysis/SelectSet.js
src/packages/@ncigdc/components/analysis/availableAnalysis.js

PRTL-3175
add demo tooltip text & intro text for gene expression

[PRTL-3175] gene expression tooltip and intro

---

package-lock.json
package.json
src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js

PRTL-3210
add jspdf to enable pdf downloads

[PRTL-3210] gene ex: save to pdf

---

src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js

Ensures the correct centring of the colour scale.

[PRTL-3234] recentre inchlib scale gradient

---

src/packages/@ncigdc/components/analysis/geneExpression/ValidationResults.js
src/packages/@ncigdc/components/analysis/geneExpression/helpers.js
src/packages/@ncigdc/uikit/WarningBox.js

Corrects the minimum GE datapoints, and improves the error feedback message and layout.

[PRTL-3240] correct minimum number of GE datapoints

---

src/packages/@ncigdc/components/analysis/AnalysisResult.js
src/packages/@ncigdc/components/analysis/CreateAnalysis.js
src/packages/@ncigdc/components/analysis/SelectSet.js
src/packages/@ncigdc/components/analysis/availableAnalysis.js
src/packages/@ncigdc/modern_components/GeneExpression/GeneExpression.js
src/packages/@ncigdc/uikit/Chip/index.js
src/packages/@ncigdc/uikit/Chip/styles.scss

Adds a new component (Chip), and uses it to display a sign for the users to know Gene Expression is still to be considered Work in Progress. 
The manner I've implemented this, makes it easy to display future analyses as "Beta" as well.

[PRTL-3243] add BETA tag + text across Gene Expression

---

src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js

Changes the label for the Gene Expression "reset" button, to improve clarity of its function.

[PRTL-3245] change inchlib “reset zoom level” label

---

src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js

PRTL-3247
add axis labels to inchlib/gene expression

[PRTL-3247] gene ex: add axis labels

---

src/packages/@ncigdc/modern_components/GeneExpression/GeneExpressionChart.js
src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js

PRTL-3260
add `destroy` event to inchlib to fix memory leak

[PRTL-3260] inchlib - cleanup on unmount

---

src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js

PRTL-3261
- add units to age @ dx
- make legend wider to accommodate

[PRTL-3261] gene ex: add units to age @ dx

---

src/packages/@ncigdc/components/analysis/geneExpression/ValidationResults.js

PRTL-3263
update tooMany message

[PRTL-3263] gene ex: update tooMany message

---

src/packages/@ncigdc/components/EntityPageHorizontalTable.js
src/packages/@ncigdc/components/analysis/CreateAnalysis.js
src/packages/@ncigdc/components/analysis/DemoButton.js
src/packages/@ncigdc/components/analysis/SelectSet.js
src/packages/@ncigdc/components/analysis/availableAnalysis.js
src/packages/@ncigdc/components/analysis/geneExpression/ValidationResults.js
src/packages/@ncigdc/modern_components/GeneExpression/GeneExpression.js

Adds cards with details about the sets at the Gene Expression analysis

[PRTL-3248] add GeneEx set details  box

---

src/packages/@ncigdc/modern_components/GeneExpression/GeneExpressionChart.js
src/packages/@ncigdc/modern_components/GeneExpression/inchlib/index.js

Refactors inchlib's colour assignment, to account for median centring.

[PRTL-3272] improve GeneEx median colour assignment

---

src/packages/@ncigdc/components/GitHut/draw.js

PRTL-3262
correct counts on projects graph

[PRTL-3262] correct counts on projects graph

---

src/packages/@ncigdc/components/analysis/SetTable.js
src/packages/@ncigdc/components/analysis/availableAnalysis.js
src/packages/@ncigdc/modern_components/GeneExpression/DemoDescription.js
src/packages/@ncigdc/modern_components/GeneExpression/GeneExpression.js
src/packages/@ncigdc/uikit/UnstyledButton.js

[PRTL-3271] add extra instructions for gene set selection at GeneEx

---

src/packages/@ncigdc/components/analysis/availableAnalysis.js
src/packages/@ncigdc/utils/constants.js

Removes the flag for scRNAseq, making it public.

[PRTL-3280] remove scRNAseq flag. enable feature publicly

---

src/packages/@ncigdc/components/analysis/availableAnalysis.js
src/packages/@ncigdc/modern_components/GeneExpression/DemoDescription.js

Improves the demo verbiage for Gene Expression.

[PRTL-3286] change GeneEx demo text

---

src/packages/@ncigdc/modern_components/SCRNASeq/SCRNASeq.relay.js
src/packages/@ncigdc/modern_components/SCRNASeq/SCRNASeqPlot/SCRNASeqPlot.js

PRTL-3287
completely reset the plot on reset

[PRTL-3287] scrna: reset legend

---

src/packages/@ncigdc/modern_components/SCRNASeq/SCRNASeq.js

PRTL-3288
add demo text to scrna

[PRTL-3288] add demo text to scrna

---

.secrets.baseline
Dockerfile
awgportal.Dockerfile
portal.Dockerfile

https://jira.opensciencedatacloud.org/browse/GDCDEVOPS-675

Updating base images tag

---

package-lock.json
package.json

e.g. DEV-488
Final package version

final package version for yertle

---

src/packages/@ncigdc/modern_components/ClinicalCard/ClinicalCard.js

DEV-620
Make button text more descriptive to alert users that they can download the complete data set for follow ups. Tool tip further indicates that this is only possible with the json download.

DEV-620: Update btn text and add tooltip

---

src/packages/@ncigdc/components/Footer.js

PEAR-318
Adds HHS Vulnerability Disclosure link to footer

Add HHS Vulnerability Disclosure link

---

.secrets.baseline
package.json
public/index.html

The NCI is changing how their analytics scripts are loaded.  This commit removes the old script and add the new one.

PEAR-804 switch to new analytics

---

.secrets.baseline
build.sh
package.json
portal.Dockerfile
public/index.html

DEV-1669: Merge release/elion into master
